#pragma once

// map group ids
// `newgroup` indexes are for:
// - MapGroupPointers (see data/maps/maps.asm)
// - MapGroupRoofs (see data/maps/roofs.asm)
// - OutdoorSprites (see data/maps/outdoor_sprites.asm)
// - RoofPals (see gfx/tilesets/roofs.pal)
// `map_const` indexes are for the sub-tables of MapGroupPointers (see data/maps/maps.asm)
// Each map also has associated data:
// - attributes (see data/maps/attributes.asm)
// - blocks (see data/maps/blocks.asm)
// - scripts and events (see data/maps/scripts.asm)

#define MAPGROUP_OLIVINE 1
#define GROUP_OLIVINE_POKECENTER_1F 1
#define MAP_OLIVINE_POKECENTER_1F 1
#define OLIVINE_POKECENTER_1F_WIDTH 5
#define OLIVINE_POKECENTER_1F_HEIGHT 4

#define GROUP_OLIVINE_GYM 1
#define MAP_OLIVINE_GYM 2
#define OLIVINE_GYM_WIDTH 5
#define OLIVINE_GYM_HEIGHT 8

#define GROUP_OLIVINE_TIMS_HOUSE 1
#define MAP_OLIVINE_TIMS_HOUSE 3
#define OLIVINE_TIMS_HOUSE_WIDTH 4
#define OLIVINE_TIMS_HOUSE_HEIGHT 4

#define GROUP_OLIVINE_HOUSE_BETA 1
#define MAP_OLIVINE_HOUSE_BETA 4
#define OLIVINE_HOUSE_BETA_WIDTH 4
#define OLIVINE_HOUSE_BETA_HEIGHT 4

#define GROUP_OLIVINE_PUNISHMENT_SPEECH_HOUSE 1
#define MAP_OLIVINE_PUNISHMENT_SPEECH_HOUSE 5
#define OLIVINE_PUNISHMENT_SPEECH_HOUSE_WIDTH 4
#define OLIVINE_PUNISHMENT_SPEECH_HOUSE_HEIGHT 4

#define GROUP_OLIVINE_GOOD_ROD_HOUSE 1
#define MAP_OLIVINE_GOOD_ROD_HOUSE 6
#define OLIVINE_GOOD_ROD_HOUSE_WIDTH 4
#define OLIVINE_GOOD_ROD_HOUSE_HEIGHT 4

#define GROUP_OLIVINE_CAFE 1
#define MAP_OLIVINE_CAFE 7
#define OLIVINE_CAFE_WIDTH 4
#define OLIVINE_CAFE_HEIGHT 4

#define GROUP_OLIVINE_MART 1
#define MAP_OLIVINE_MART 8
#define OLIVINE_MART_WIDTH 6
#define OLIVINE_MART_HEIGHT 4

#define GROUP_ROUTE_38_ECRUTEAK_GATE 1
#define MAP_ROUTE_38_ECRUTEAK_GATE 9
#define ROUTE_38_ECRUTEAK_GATE_WIDTH 5
#define ROUTE_38_ECRUTEAK_GATE_HEIGHT 4

#define GROUP_ROUTE_39_BARN 1
#define MAP_ROUTE_39_BARN 10
#define ROUTE_39_BARN_WIDTH 4
#define ROUTE_39_BARN_HEIGHT 4

#define GROUP_ROUTE_39_FARMHOUSE 1
#define MAP_ROUTE_39_FARMHOUSE 11
#define ROUTE_39_FARMHOUSE_WIDTH 4
#define ROUTE_39_FARMHOUSE_HEIGHT 4

#define GROUP_ROUTE_38 1
#define MAP_ROUTE_38 12
#define ROUTE_38_WIDTH 20
#define ROUTE_38_HEIGHT 9

#define GROUP_ROUTE_39 1
#define MAP_ROUTE_39 13
#define ROUTE_39_WIDTH 10
#define ROUTE_39_HEIGHT 18

#define GROUP_OLIVINE_CITY 1
#define MAP_OLIVINE_CITY 14
#define OLIVINE_CITY_WIDTH 20
#define OLIVINE_CITY_HEIGHT 18


#define MAPGROUP_MAHOGANY 2
#define GROUP_MAHOGANY_RED_GYARADOS_SPEECH_HOUSE 2
#define MAP_MAHOGANY_RED_GYARADOS_SPEECH_HOUSE 1
#define MAHOGANY_RED_GYARADOS_SPEECH_HOUSE_WIDTH 4
#define MAHOGANY_RED_GYARADOS_SPEECH_HOUSE_HEIGHT 4

#define GROUP_MAHOGANY_GYM 2
#define MAP_MAHOGANY_GYM 2
#define MAHOGANY_GYM_WIDTH 5
#define MAHOGANY_GYM_HEIGHT 9

#define GROUP_MAHOGANY_POKECENTER_1F 2
#define MAP_MAHOGANY_POKECENTER_1F 3
#define MAHOGANY_POKECENTER_1F_WIDTH 5
#define MAHOGANY_POKECENTER_1F_HEIGHT 4

#define GROUP_ROUTE_42_ECRUTEAK_GATE 2
#define MAP_ROUTE_42_ECRUTEAK_GATE 4
#define ROUTE_42_ECRUTEAK_GATE_WIDTH 5
#define ROUTE_42_ECRUTEAK_GATE_HEIGHT 4

#define GROUP_ROUTE_42 2
#define MAP_ROUTE_42 5
#define ROUTE_42_WIDTH 30
#define ROUTE_42_HEIGHT 9

#define GROUP_ROUTE_44 2
#define MAP_ROUTE_44 6
#define ROUTE_44_WIDTH 30
#define ROUTE_44_HEIGHT 9

#define GROUP_MAHOGANY_TOWN 2
#define MAP_MAHOGANY_TOWN 7
#define MAHOGANY_TOWN_WIDTH 10
#define MAHOGANY_TOWN_HEIGHT 9


#define MAPGROUP_DUNGEONS 3
#define GROUP_SPROUT_TOWER_1F 3
#define MAP_SPROUT_TOWER_1F 1
#define SPROUT_TOWER_1F_WIDTH 10
#define SPROUT_TOWER_1F_HEIGHT 8

#define GROUP_SPROUT_TOWER_2F 3
#define MAP_SPROUT_TOWER_2F 2
#define SPROUT_TOWER_2F_WIDTH 10
#define SPROUT_TOWER_2F_HEIGHT 8

#define GROUP_SPROUT_TOWER_3F 3
#define MAP_SPROUT_TOWER_3F 3
#define SPROUT_TOWER_3F_WIDTH 10
#define SPROUT_TOWER_3F_HEIGHT 8

#define GROUP_TIN_TOWER_1F 3
#define MAP_TIN_TOWER_1F 4
#define TIN_TOWER_1F_WIDTH 10
#define TIN_TOWER_1F_HEIGHT 9

#define GROUP_TIN_TOWER_2F 3
#define MAP_TIN_TOWER_2F 5
#define TIN_TOWER_2F_WIDTH 10
#define TIN_TOWER_2F_HEIGHT 9

#define GROUP_TIN_TOWER_3F 3
#define MAP_TIN_TOWER_3F 6
#define TIN_TOWER_3F_WIDTH 10
#define TIN_TOWER_3F_HEIGHT 9

#define GROUP_TIN_TOWER_4F 3
#define MAP_TIN_TOWER_4F 7
#define TIN_TOWER_4F_WIDTH 10
#define TIN_TOWER_4F_HEIGHT 9

#define GROUP_TIN_TOWER_5F 3
#define MAP_TIN_TOWER_5F 8
#define TIN_TOWER_5F_WIDTH 10
#define TIN_TOWER_5F_HEIGHT 9

#define GROUP_TIN_TOWER_6F 3
#define MAP_TIN_TOWER_6F 9
#define TIN_TOWER_6F_WIDTH 10
#define TIN_TOWER_6F_HEIGHT 9

#define GROUP_TIN_TOWER_7F 3
#define MAP_TIN_TOWER_7F 10
#define TIN_TOWER_7F_WIDTH 10
#define TIN_TOWER_7F_HEIGHT 9

#define GROUP_TIN_TOWER_8F 3
#define MAP_TIN_TOWER_8F 11
#define TIN_TOWER_8F_WIDTH 10
#define TIN_TOWER_8F_HEIGHT 9

#define GROUP_TIN_TOWER_9F 3
#define MAP_TIN_TOWER_9F 12
#define TIN_TOWER_9F_WIDTH 10
#define TIN_TOWER_9F_HEIGHT 9

#define GROUP_BURNED_TOWER_1F 3
#define MAP_BURNED_TOWER_1F 13
#define BURNED_TOWER_1F_WIDTH 10
#define BURNED_TOWER_1F_HEIGHT 9

#define GROUP_BURNED_TOWER_B1F 3
#define MAP_BURNED_TOWER_B1F 14
#define BURNED_TOWER_B1F_WIDTH 10
#define BURNED_TOWER_B1F_HEIGHT 9

#define GROUP_NATIONAL_PARK 3
#define MAP_NATIONAL_PARK 15
#define NATIONAL_PARK_WIDTH 20
#define NATIONAL_PARK_HEIGHT 27

#define GROUP_NATIONAL_PARK_BUG_CONTEST 3
#define MAP_NATIONAL_PARK_BUG_CONTEST 16
#define NATIONAL_PARK_BUG_CONTEST_WIDTH 20
#define NATIONAL_PARK_BUG_CONTEST_HEIGHT 27

#define GROUP_RADIO_TOWER_1F 3
#define MAP_RADIO_TOWER_1F 17
#define RADIO_TOWER_1F_WIDTH 9
#define RADIO_TOWER_1F_HEIGHT 4

#define GROUP_RADIO_TOWER_2F 3
#define MAP_RADIO_TOWER_2F 18
#define RADIO_TOWER_2F_WIDTH 9
#define RADIO_TOWER_2F_HEIGHT 4

#define GROUP_RADIO_TOWER_3F 3
#define MAP_RADIO_TOWER_3F 19
#define RADIO_TOWER_3F_WIDTH 9
#define RADIO_TOWER_3F_HEIGHT 4

#define GROUP_RADIO_TOWER_4F 3
#define MAP_RADIO_TOWER_4F 20
#define RADIO_TOWER_4F_WIDTH 9
#define RADIO_TOWER_4F_HEIGHT 4

#define GROUP_RADIO_TOWER_5F 3
#define MAP_RADIO_TOWER_5F 21
#define RADIO_TOWER_5F_WIDTH 9
#define RADIO_TOWER_5F_HEIGHT 4

#define GROUP_RUINS_OF_ALPH_OUTSIDE 3
#define MAP_RUINS_OF_ALPH_OUTSIDE 22
#define RUINS_OF_ALPH_OUTSIDE_WIDTH 10
#define RUINS_OF_ALPH_OUTSIDE_HEIGHT 18

#define GROUP_RUINS_OF_ALPH_HO_OH_CHAMBER 3
#define MAP_RUINS_OF_ALPH_HO_OH_CHAMBER 23
#define RUINS_OF_ALPH_HO_OH_CHAMBER_WIDTH 4
#define RUINS_OF_ALPH_HO_OH_CHAMBER_HEIGHT 5

#define GROUP_RUINS_OF_ALPH_KABUTO_CHAMBER 3
#define MAP_RUINS_OF_ALPH_KABUTO_CHAMBER 24
#define RUINS_OF_ALPH_KABUTO_CHAMBER_WIDTH 4
#define RUINS_OF_ALPH_KABUTO_CHAMBER_HEIGHT 5

#define GROUP_RUINS_OF_ALPH_OMANYTE_CHAMBER 3
#define MAP_RUINS_OF_ALPH_OMANYTE_CHAMBER 25
#define RUINS_OF_ALPH_OMANYTE_CHAMBER_WIDTH 4
#define RUINS_OF_ALPH_OMANYTE_CHAMBER_HEIGHT 5

#define GROUP_RUINS_OF_ALPH_AERODACTYL_CHAMBER 3
#define MAP_RUINS_OF_ALPH_AERODACTYL_CHAMBER 26
#define RUINS_OF_ALPH_AERODACTYL_CHAMBER_WIDTH 4
#define RUINS_OF_ALPH_AERODACTYL_CHAMBER_HEIGHT 5

#define GROUP_RUINS_OF_ALPH_INNER_CHAMBER 3
#define MAP_RUINS_OF_ALPH_INNER_CHAMBER 27
#define RUINS_OF_ALPH_INNER_CHAMBER_WIDTH 10
#define RUINS_OF_ALPH_INNER_CHAMBER_HEIGHT 14

#define GROUP_RUINS_OF_ALPH_RESEARCH_CENTER 3
#define MAP_RUINS_OF_ALPH_RESEARCH_CENTER 28
#define RUINS_OF_ALPH_RESEARCH_CENTER_WIDTH 4
#define RUINS_OF_ALPH_RESEARCH_CENTER_HEIGHT 4

#define GROUP_UNION_CAVE_1F 3
#define MAP_UNION_CAVE_1F 29
#define UNION_CAVE_1F_WIDTH 10
#define UNION_CAVE_1F_HEIGHT 18

#define GROUP_UNION_CAVE_B1F 3
#define MAP_UNION_CAVE_B1F 30
#define UNION_CAVE_B1F_WIDTH 10
#define UNION_CAVE_B1F_HEIGHT 18

#define GROUP_UNION_CAVE_B2F 3
#define MAP_UNION_CAVE_B2F 31
#define UNION_CAVE_B2F_WIDTH 10
#define UNION_CAVE_B2F_HEIGHT 18

#define GROUP_SLOWPOKE_WELL_B1F 3
#define MAP_SLOWPOKE_WELL_B1F 32
#define SLOWPOKE_WELL_B1F_WIDTH 10
#define SLOWPOKE_WELL_B1F_HEIGHT 9

#define GROUP_SLOWPOKE_WELL_B2F 3
#define MAP_SLOWPOKE_WELL_B2F 33
#define SLOWPOKE_WELL_B2F_WIDTH 10
#define SLOWPOKE_WELL_B2F_HEIGHT 9

#define GROUP_OLIVINE_LIGHTHOUSE_1F 3
#define MAP_OLIVINE_LIGHTHOUSE_1F 34
#define OLIVINE_LIGHTHOUSE_1F_WIDTH 10
#define OLIVINE_LIGHTHOUSE_1F_HEIGHT 9

#define GROUP_OLIVINE_LIGHTHOUSE_2F 3
#define MAP_OLIVINE_LIGHTHOUSE_2F 35
#define OLIVINE_LIGHTHOUSE_2F_WIDTH 10
#define OLIVINE_LIGHTHOUSE_2F_HEIGHT 9

#define GROUP_OLIVINE_LIGHTHOUSE_3F 3
#define MAP_OLIVINE_LIGHTHOUSE_3F 36
#define OLIVINE_LIGHTHOUSE_3F_WIDTH 10
#define OLIVINE_LIGHTHOUSE_3F_HEIGHT 9

#define GROUP_OLIVINE_LIGHTHOUSE_4F 3
#define MAP_OLIVINE_LIGHTHOUSE_4F 37
#define OLIVINE_LIGHTHOUSE_4F_WIDTH 10
#define OLIVINE_LIGHTHOUSE_4F_HEIGHT 9

#define GROUP_OLIVINE_LIGHTHOUSE_5F 3
#define MAP_OLIVINE_LIGHTHOUSE_5F 38
#define OLIVINE_LIGHTHOUSE_5F_WIDTH 10
#define OLIVINE_LIGHTHOUSE_5F_HEIGHT 9

#define GROUP_OLIVINE_LIGHTHOUSE_6F 3
#define MAP_OLIVINE_LIGHTHOUSE_6F 39
#define OLIVINE_LIGHTHOUSE_6F_WIDTH 10
#define OLIVINE_LIGHTHOUSE_6F_HEIGHT 9

#define GROUP_MAHOGANY_MART_1F 3
#define MAP_MAHOGANY_MART_1F 40
#define MAHOGANY_MART_1F_WIDTH 4
#define MAHOGANY_MART_1F_HEIGHT 4

#define GROUP_TEAM_ROCKET_BASE_B1F 3
#define MAP_TEAM_ROCKET_BASE_B1F 41
#define TEAM_ROCKET_BASE_B1F_WIDTH 15
#define TEAM_ROCKET_BASE_B1F_HEIGHT 9

#define GROUP_TEAM_ROCKET_BASE_B2F 3
#define MAP_TEAM_ROCKET_BASE_B2F 42
#define TEAM_ROCKET_BASE_B2F_WIDTH 15
#define TEAM_ROCKET_BASE_B2F_HEIGHT 9

#define GROUP_TEAM_ROCKET_BASE_B3F 3
#define MAP_TEAM_ROCKET_BASE_B3F 43
#define TEAM_ROCKET_BASE_B3F_WIDTH 15
#define TEAM_ROCKET_BASE_B3F_HEIGHT 9

#define GROUP_ILEX_FOREST 3
#define MAP_ILEX_FOREST 44
#define ILEX_FOREST_WIDTH 15
#define ILEX_FOREST_HEIGHT 27

#define GROUP_GOLDENROD_UNDERGROUND 3
#define MAP_GOLDENROD_UNDERGROUND 45
#define GOLDENROD_UNDERGROUND_WIDTH 15
#define GOLDENROD_UNDERGROUND_HEIGHT 18

#define GROUP_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES 3
#define MAP_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES 46
#define GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_WIDTH 15
#define GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HEIGHT 18

#define GROUP_GOLDENROD_DEPT_STORE_B1F 3
#define MAP_GOLDENROD_DEPT_STORE_B1F 47
#define GOLDENROD_DEPT_STORE_B1F_WIDTH 10
#define GOLDENROD_DEPT_STORE_B1F_HEIGHT 9

#define GROUP_GOLDENROD_UNDERGROUND_WAREHOUSE 3
#define MAP_GOLDENROD_UNDERGROUND_WAREHOUSE 48
#define GOLDENROD_UNDERGROUND_WAREHOUSE_WIDTH 10
#define GOLDENROD_UNDERGROUND_WAREHOUSE_HEIGHT 9

#define GROUP_MOUNT_MORTAR_1F_OUTSIDE 3
#define MAP_MOUNT_MORTAR_1F_OUTSIDE 49
#define MOUNT_MORTAR_1F_OUTSIDE_WIDTH 20
#define MOUNT_MORTAR_1F_OUTSIDE_HEIGHT 18

#define GROUP_MOUNT_MORTAR_1F_INSIDE 3
#define MAP_MOUNT_MORTAR_1F_INSIDE 50
#define MOUNT_MORTAR_1F_INSIDE_WIDTH 20
#define MOUNT_MORTAR_1F_INSIDE_HEIGHT 27

#define GROUP_MOUNT_MORTAR_2F_INSIDE 3
#define MAP_MOUNT_MORTAR_2F_INSIDE 51
#define MOUNT_MORTAR_2F_INSIDE_WIDTH 20
#define MOUNT_MORTAR_2F_INSIDE_HEIGHT 18

#define GROUP_MOUNT_MORTAR_B1F 3
#define MAP_MOUNT_MORTAR_B1F 52
#define MOUNT_MORTAR_B1F_WIDTH 20
#define MOUNT_MORTAR_B1F_HEIGHT 18

#define GROUP_ICE_PATH_1F 3
#define MAP_ICE_PATH_1F 53
#define ICE_PATH_1F_WIDTH 20
#define ICE_PATH_1F_HEIGHT 18

#define GROUP_ICE_PATH_B1F 3
#define MAP_ICE_PATH_B1F 54
#define ICE_PATH_B1F_WIDTH 10
#define ICE_PATH_B1F_HEIGHT 18

#define GROUP_ICE_PATH_B2F_MAHOGANY_SIDE 3
#define MAP_ICE_PATH_B2F_MAHOGANY_SIDE 55
#define ICE_PATH_B2F_MAHOGANY_SIDE_WIDTH 10
#define ICE_PATH_B2F_MAHOGANY_SIDE_HEIGHT 9

#define GROUP_ICE_PATH_B2F_BLACKTHORN_SIDE 3
#define MAP_ICE_PATH_B2F_BLACKTHORN_SIDE 56
#define ICE_PATH_B2F_BLACKTHORN_SIDE_WIDTH 5
#define ICE_PATH_B2F_BLACKTHORN_SIDE_HEIGHT 9

#define GROUP_ICE_PATH_B3F 3
#define MAP_ICE_PATH_B3F 57
#define ICE_PATH_B3F_WIDTH 10
#define ICE_PATH_B3F_HEIGHT 9

#define GROUP_WHIRL_ISLAND_NW 3
#define MAP_WHIRL_ISLAND_NW 58
#define WHIRL_ISLAND_NW_WIDTH 5
#define WHIRL_ISLAND_NW_HEIGHT 9

#define GROUP_WHIRL_ISLAND_NE 3
#define MAP_WHIRL_ISLAND_NE 59
#define WHIRL_ISLAND_NE_WIDTH 10
#define WHIRL_ISLAND_NE_HEIGHT 9

#define GROUP_WHIRL_ISLAND_SW 3
#define MAP_WHIRL_ISLAND_SW 60
#define WHIRL_ISLAND_SW_WIDTH 10
#define WHIRL_ISLAND_SW_HEIGHT 9

#define GROUP_WHIRL_ISLAND_CAVE 3
#define MAP_WHIRL_ISLAND_CAVE 61
#define WHIRL_ISLAND_CAVE_WIDTH 5
#define WHIRL_ISLAND_CAVE_HEIGHT 9

#define GROUP_WHIRL_ISLAND_SE 3
#define MAP_WHIRL_ISLAND_SE 62
#define WHIRL_ISLAND_SE_WIDTH 5
#define WHIRL_ISLAND_SE_HEIGHT 9

#define GROUP_WHIRL_ISLAND_B1F 3
#define MAP_WHIRL_ISLAND_B1F 63
#define WHIRL_ISLAND_B1F_WIDTH 20
#define WHIRL_ISLAND_B1F_HEIGHT 18

#define GROUP_WHIRL_ISLAND_B2F 3
#define MAP_WHIRL_ISLAND_B2F 64
#define WHIRL_ISLAND_B2F_WIDTH 10
#define WHIRL_ISLAND_B2F_HEIGHT 18

#define GROUP_WHIRL_ISLAND_LUGIA_CHAMBER 3
#define MAP_WHIRL_ISLAND_LUGIA_CHAMBER 65
#define WHIRL_ISLAND_LUGIA_CHAMBER_WIDTH 10
#define WHIRL_ISLAND_LUGIA_CHAMBER_HEIGHT 9

#define GROUP_SILVER_CAVE_ROOM_1 3
#define MAP_SILVER_CAVE_ROOM_1 66
#define SILVER_CAVE_ROOM_1_WIDTH 10
#define SILVER_CAVE_ROOM_1_HEIGHT 18

#define GROUP_SILVER_CAVE_ROOM_2 3
#define MAP_SILVER_CAVE_ROOM_2 67
#define SILVER_CAVE_ROOM_2_WIDTH 15
#define SILVER_CAVE_ROOM_2_HEIGHT 18

#define GROUP_SILVER_CAVE_ROOM_3 3
#define MAP_SILVER_CAVE_ROOM_3 68
#define SILVER_CAVE_ROOM_3_WIDTH 10
#define SILVER_CAVE_ROOM_3_HEIGHT 18

#define GROUP_SILVER_CAVE_ITEM_ROOMS 3
#define MAP_SILVER_CAVE_ITEM_ROOMS 69
#define SILVER_CAVE_ITEM_ROOMS_WIDTH 10
#define SILVER_CAVE_ITEM_ROOMS_HEIGHT 9

#define GROUP_DARK_CAVE_VIOLET_ENTRANCE 3
#define MAP_DARK_CAVE_VIOLET_ENTRANCE 70
#define DARK_CAVE_VIOLET_ENTRANCE_WIDTH 20
#define DARK_CAVE_VIOLET_ENTRANCE_HEIGHT 18

#define GROUP_DARK_CAVE_BLACKTHORN_ENTRANCE 3
#define MAP_DARK_CAVE_BLACKTHORN_ENTRANCE 71
#define DARK_CAVE_BLACKTHORN_ENTRANCE_WIDTH 15
#define DARK_CAVE_BLACKTHORN_ENTRANCE_HEIGHT 18

#define GROUP_DRAGONS_DEN_1F 3
#define MAP_DRAGONS_DEN_1F 72
#define DRAGONS_DEN_1F_WIDTH 5
#define DRAGONS_DEN_1F_HEIGHT 9

#define GROUP_DRAGONS_DEN_B1F 3
#define MAP_DRAGONS_DEN_B1F 73
#define DRAGONS_DEN_B1F_WIDTH 20
#define DRAGONS_DEN_B1F_HEIGHT 18

#define GROUP_TOHJO_FALLS 3
#define MAP_TOHJO_FALLS 74
#define TOHJO_FALLS_WIDTH 15
#define TOHJO_FALLS_HEIGHT 9

#define GROUP_DIGLETTS_CAVE 3
#define MAP_DIGLETTS_CAVE 75
#define DIGLETTS_CAVE_WIDTH 10
#define DIGLETTS_CAVE_HEIGHT 18

#define GROUP_MOUNT_MOON 3
#define MAP_MOUNT_MOON 76
#define MOUNT_MOON_WIDTH 15
#define MOUNT_MOON_HEIGHT 9

#define GROUP_UNDERGROUND_PATH 3
#define MAP_UNDERGROUND_PATH 77
#define UNDERGROUND_PATH_WIDTH 3
#define UNDERGROUND_PATH_HEIGHT 14

#define GROUP_ROCK_TUNNEL_1F 3
#define MAP_ROCK_TUNNEL_1F 78
#define ROCK_TUNNEL_1F_WIDTH 15
#define ROCK_TUNNEL_1F_HEIGHT 18

#define GROUP_ROCK_TUNNEL_B1F 3
#define MAP_ROCK_TUNNEL_B1F 79
#define ROCK_TUNNEL_B1F_WIDTH 15
#define ROCK_TUNNEL_B1F_HEIGHT 18

#define GROUP_SAFARI_ZONE_FUCHSIA_GATE_BETA 3
#define MAP_SAFARI_ZONE_FUCHSIA_GATE_BETA 80
#define SAFARI_ZONE_FUCHSIA_GATE_BETA_WIDTH 5
#define SAFARI_ZONE_FUCHSIA_GATE_BETA_HEIGHT 4

#define GROUP_SAFARI_ZONE_BETA 3
#define MAP_SAFARI_ZONE_BETA 81
#define SAFARI_ZONE_BETA_WIDTH 10
#define SAFARI_ZONE_BETA_HEIGHT 18

#define GROUP_VICTORY_ROAD 3
#define MAP_VICTORY_ROAD 82
#define VICTORY_ROAD_WIDTH 10
#define VICTORY_ROAD_HEIGHT 36


#define MAPGROUP_ECRUTEAK 4
#define GROUP_ECRUTEAK_TIN_TOWER_ENTRANCE 4
#define MAP_ECRUTEAK_TIN_TOWER_ENTRANCE 1
#define ECRUTEAK_TIN_TOWER_ENTRANCE_WIDTH 10
#define ECRUTEAK_TIN_TOWER_ENTRANCE_HEIGHT 9

#define GROUP_ECRUTEAK_TIN_TOWER_BACK_ENTRANCE 4
#define MAP_ECRUTEAK_TIN_TOWER_BACK_ENTRANCE 2
#define ECRUTEAK_TIN_TOWER_BACK_ENTRANCE_WIDTH 4
#define ECRUTEAK_TIN_TOWER_BACK_ENTRANCE_HEIGHT 4

#define GROUP_ECRUTEAK_POKECENTER_1F 4
#define MAP_ECRUTEAK_POKECENTER_1F 3
#define ECRUTEAK_POKECENTER_1F_WIDTH 5
#define ECRUTEAK_POKECENTER_1F_HEIGHT 4

#define GROUP_ECRUTEAK_LUGIA_SPEECH_HOUSE 4
#define MAP_ECRUTEAK_LUGIA_SPEECH_HOUSE 4
#define ECRUTEAK_LUGIA_SPEECH_HOUSE_WIDTH 4
#define ECRUTEAK_LUGIA_SPEECH_HOUSE_HEIGHT 4

#define GROUP_DANCE_THEATRE 4
#define MAP_DANCE_THEATRE 5
#define DANCE_THEATRE_WIDTH 6
#define DANCE_THEATRE_HEIGHT 7

#define GROUP_ECRUTEAK_MART 4
#define MAP_ECRUTEAK_MART 6
#define ECRUTEAK_MART_WIDTH 6
#define ECRUTEAK_MART_HEIGHT 4

#define GROUP_ECRUTEAK_GYM 4
#define MAP_ECRUTEAK_GYM 7
#define ECRUTEAK_GYM_WIDTH 5
#define ECRUTEAK_GYM_HEIGHT 9

#define GROUP_ECRUTEAK_ITEMFINDER_HOUSE 4
#define MAP_ECRUTEAK_ITEMFINDER_HOUSE 8
#define ECRUTEAK_ITEMFINDER_HOUSE_WIDTH 4
#define ECRUTEAK_ITEMFINDER_HOUSE_HEIGHT 4

#define GROUP_ECRUTEAK_CITY 4
#define MAP_ECRUTEAK_CITY 9
#define ECRUTEAK_CITY_WIDTH 20
#define ECRUTEAK_CITY_HEIGHT 18


#define MAPGROUP_BLACKTHORN 5
#define GROUP_BLACKTHORN_GYM_1F 5
#define MAP_BLACKTHORN_GYM_1F 1
#define BLACKTHORN_GYM_1F_WIDTH 5
#define BLACKTHORN_GYM_1F_HEIGHT 9

#define GROUP_BLACKTHORN_GYM_2F 5
#define MAP_BLACKTHORN_GYM_2F 2
#define BLACKTHORN_GYM_2F_WIDTH 5
#define BLACKTHORN_GYM_2F_HEIGHT 9

#define GROUP_BLACKTHORN_DRAGON_SPEECH_HOUSE 5
#define MAP_BLACKTHORN_DRAGON_SPEECH_HOUSE 3
#define BLACKTHORN_DRAGON_SPEECH_HOUSE_WIDTH 4
#define BLACKTHORN_DRAGON_SPEECH_HOUSE_HEIGHT 4

#define GROUP_BLACKTHORN_EMYS_HOUSE 5
#define MAP_BLACKTHORN_EMYS_HOUSE 4
#define BLACKTHORN_EMYS_HOUSE_WIDTH 4
#define BLACKTHORN_EMYS_HOUSE_HEIGHT 4

#define GROUP_BLACKTHORN_MART 5
#define MAP_BLACKTHORN_MART 5
#define BLACKTHORN_MART_WIDTH 6
#define BLACKTHORN_MART_HEIGHT 4

#define GROUP_BLACKTHORN_POKECENTER_1F 5
#define MAP_BLACKTHORN_POKECENTER_1F 6
#define BLACKTHORN_POKECENTER_1F_WIDTH 5
#define BLACKTHORN_POKECENTER_1F_HEIGHT 4

#define GROUP_MOVE_DELETERS_HOUSE 5
#define MAP_MOVE_DELETERS_HOUSE 7
#define MOVE_DELETERS_HOUSE_WIDTH 4
#define MOVE_DELETERS_HOUSE_HEIGHT 4

#define GROUP_ROUTE_45 5
#define MAP_ROUTE_45 8
#define ROUTE_45_WIDTH 10
#define ROUTE_45_HEIGHT 45

#define GROUP_ROUTE_46 5
#define MAP_ROUTE_46 9
#define ROUTE_46_WIDTH 10
#define ROUTE_46_HEIGHT 18

#define GROUP_BLACKTHORN_CITY 5
#define MAP_BLACKTHORN_CITY 10
#define BLACKTHORN_CITY_WIDTH 20
#define BLACKTHORN_CITY_HEIGHT 18


#define MAPGROUP_CINNABAR 6
#define GROUP_CINNABAR_POKECENTER_1F 6
#define MAP_CINNABAR_POKECENTER_1F 1
#define CINNABAR_POKECENTER_1F_WIDTH 5
#define CINNABAR_POKECENTER_1F_HEIGHT 4

#define GROUP_CINNABAR_POKECENTER_2F_BETA 6
#define MAP_CINNABAR_POKECENTER_2F_BETA 2
#define CINNABAR_POKECENTER_2F_BETA_WIDTH 8
#define CINNABAR_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_ROUTE_19_FUCHSIA_GATE 6
#define MAP_ROUTE_19_FUCHSIA_GATE 3
#define ROUTE_19_FUCHSIA_GATE_WIDTH 5
#define ROUTE_19_FUCHSIA_GATE_HEIGHT 4

#define GROUP_SEAFOAM_GYM 6
#define MAP_SEAFOAM_GYM 4
#define SEAFOAM_GYM_WIDTH 5
#define SEAFOAM_GYM_HEIGHT 4

#define GROUP_ROUTE_19 6
#define MAP_ROUTE_19 5
#define ROUTE_19_WIDTH 10
#define ROUTE_19_HEIGHT 18

#define GROUP_ROUTE_20 6
#define MAP_ROUTE_20 6
#define ROUTE_20_WIDTH 30
#define ROUTE_20_HEIGHT 9

#define GROUP_ROUTE_21 6
#define MAP_ROUTE_21 7
#define ROUTE_21_WIDTH 10
#define ROUTE_21_HEIGHT 18

#define GROUP_CINNABAR_ISLAND 6
#define MAP_CINNABAR_ISLAND 8
#define CINNABAR_ISLAND_WIDTH 10
#define CINNABAR_ISLAND_HEIGHT 9


#define MAPGROUP_CERULEAN 7
#define GROUP_CERULEAN_GYM_BADGE_SPEECH_HOUSE 7
#define MAP_CERULEAN_GYM_BADGE_SPEECH_HOUSE 1
#define CERULEAN_GYM_BADGE_SPEECH_HOUSE_WIDTH 4
#define CERULEAN_GYM_BADGE_SPEECH_HOUSE_HEIGHT 4

#define GROUP_CERULEAN_POLICE_STATION 7
#define MAP_CERULEAN_POLICE_STATION 2
#define CERULEAN_POLICE_STATION_WIDTH 4
#define CERULEAN_POLICE_STATION_HEIGHT 4

#define GROUP_CERULEAN_TRADE_SPEECH_HOUSE 7
#define MAP_CERULEAN_TRADE_SPEECH_HOUSE 3
#define CERULEAN_TRADE_SPEECH_HOUSE_WIDTH 4
#define CERULEAN_TRADE_SPEECH_HOUSE_HEIGHT 4

#define GROUP_CERULEAN_POKECENTER_1F 7
#define MAP_CERULEAN_POKECENTER_1F 4
#define CERULEAN_POKECENTER_1F_WIDTH 5
#define CERULEAN_POKECENTER_1F_HEIGHT 4

#define GROUP_CERULEAN_POKECENTER_2F_BETA 7
#define MAP_CERULEAN_POKECENTER_2F_BETA 5
#define CERULEAN_POKECENTER_2F_BETA_WIDTH 8
#define CERULEAN_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_CERULEAN_GYM 7
#define MAP_CERULEAN_GYM 6
#define CERULEAN_GYM_WIDTH 5
#define CERULEAN_GYM_HEIGHT 8

#define GROUP_CERULEAN_MART 7
#define MAP_CERULEAN_MART 7
#define CERULEAN_MART_WIDTH 6
#define CERULEAN_MART_HEIGHT 4

#define GROUP_ROUTE_10_POKECENTER_1F 7
#define MAP_ROUTE_10_POKECENTER_1F 8
#define ROUTE_10_POKECENTER_1F_WIDTH 5
#define ROUTE_10_POKECENTER_1F_HEIGHT 4

#define GROUP_ROUTE_10_POKECENTER_2F_BETA 7
#define MAP_ROUTE_10_POKECENTER_2F_BETA 9
#define ROUTE_10_POKECENTER_2F_BETA_WIDTH 8
#define ROUTE_10_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_POWER_PLANT 7
#define MAP_POWER_PLANT 10
#define POWER_PLANT_WIDTH 10
#define POWER_PLANT_HEIGHT 9

#define GROUP_BILLS_HOUSE 7
#define MAP_BILLS_HOUSE 11
#define BILLS_HOUSE_WIDTH 4
#define BILLS_HOUSE_HEIGHT 4

#define GROUP_ROUTE_4 7
#define MAP_ROUTE_4 12
#define ROUTE_4_WIDTH 20
#define ROUTE_4_HEIGHT 9

#define GROUP_ROUTE_9 7
#define MAP_ROUTE_9 13
#define ROUTE_9_WIDTH 30
#define ROUTE_9_HEIGHT 9

#define GROUP_ROUTE_10_NORTH 7
#define MAP_ROUTE_10_NORTH 14
#define ROUTE_10_NORTH_WIDTH 10
#define ROUTE_10_NORTH_HEIGHT 9

#define GROUP_ROUTE_24 7
#define MAP_ROUTE_24 15
#define ROUTE_24_WIDTH 10
#define ROUTE_24_HEIGHT 9

#define GROUP_ROUTE_25 7
#define MAP_ROUTE_25 16
#define ROUTE_25_WIDTH 30
#define ROUTE_25_HEIGHT 9

#define GROUP_CERULEAN_CITY 7
#define MAP_CERULEAN_CITY 17
#define CERULEAN_CITY_WIDTH 20
#define CERULEAN_CITY_HEIGHT 18


#define MAPGROUP_AZALEA 8
#define GROUP_AZALEA_POKECENTER_1F 8
#define MAP_AZALEA_POKECENTER_1F 1
#define AZALEA_POKECENTER_1F_WIDTH 5
#define AZALEA_POKECENTER_1F_HEIGHT 4

#define GROUP_CHARCOAL_KILN 8
#define MAP_CHARCOAL_KILN 2
#define CHARCOAL_KILN_WIDTH 4
#define CHARCOAL_KILN_HEIGHT 4

#define GROUP_AZALEA_MART 8
#define MAP_AZALEA_MART 3
#define AZALEA_MART_WIDTH 6
#define AZALEA_MART_HEIGHT 4

#define GROUP_KURTS_HOUSE 8
#define MAP_KURTS_HOUSE 4
#define KURTS_HOUSE_WIDTH 8
#define KURTS_HOUSE_HEIGHT 4

#define GROUP_AZALEA_GYM 8
#define MAP_AZALEA_GYM 5
#define AZALEA_GYM_WIDTH 5
#define AZALEA_GYM_HEIGHT 8

#define GROUP_ROUTE_33 8
#define MAP_ROUTE_33 6
#define ROUTE_33_WIDTH 10
#define ROUTE_33_HEIGHT 9

#define GROUP_AZALEA_TOWN 8
#define MAP_AZALEA_TOWN 7
#define AZALEA_TOWN_WIDTH 20
#define AZALEA_TOWN_HEIGHT 9


#define MAPGROUP_LAKE_OF_RAGE 9
#define GROUP_LAKE_OF_RAGE_HIDDEN_POWER_HOUSE 9
#define MAP_LAKE_OF_RAGE_HIDDEN_POWER_HOUSE 1
#define LAKE_OF_RAGE_HIDDEN_POWER_HOUSE_WIDTH 4
#define LAKE_OF_RAGE_HIDDEN_POWER_HOUSE_HEIGHT 4

#define GROUP_LAKE_OF_RAGE_MAGIKARP_HOUSE 9
#define MAP_LAKE_OF_RAGE_MAGIKARP_HOUSE 2
#define LAKE_OF_RAGE_MAGIKARP_HOUSE_WIDTH 4
#define LAKE_OF_RAGE_MAGIKARP_HOUSE_HEIGHT 4

#define GROUP_ROUTE_43_MAHOGANY_GATE 9
#define MAP_ROUTE_43_MAHOGANY_GATE 3
#define ROUTE_43_MAHOGANY_GATE_WIDTH 5
#define ROUTE_43_MAHOGANY_GATE_HEIGHT 4

#define GROUP_ROUTE_43_GATE 9
#define MAP_ROUTE_43_GATE 4
#define ROUTE_43_GATE_WIDTH 5
#define ROUTE_43_GATE_HEIGHT 4

#define GROUP_ROUTE_43 9
#define MAP_ROUTE_43 5
#define ROUTE_43_WIDTH 10
#define ROUTE_43_HEIGHT 27

#define GROUP_LAKE_OF_RAGE 9
#define MAP_LAKE_OF_RAGE 6
#define LAKE_OF_RAGE_WIDTH 20
#define LAKE_OF_RAGE_HEIGHT 18


#define MAPGROUP_VIOLET 10
#define GROUP_ROUTE_32 10
#define MAP_ROUTE_32 1
#define ROUTE_32_WIDTH 10
#define ROUTE_32_HEIGHT 45

#define GROUP_ROUTE_35 10
#define MAP_ROUTE_35 2
#define ROUTE_35_WIDTH 10
#define ROUTE_35_HEIGHT 18

#define GROUP_ROUTE_36 10
#define MAP_ROUTE_36 3
#define ROUTE_36_WIDTH 30
#define ROUTE_36_HEIGHT 9

#define GROUP_ROUTE_37 10
#define MAP_ROUTE_37 4
#define ROUTE_37_WIDTH 10
#define ROUTE_37_HEIGHT 9

#define GROUP_VIOLET_CITY 10
#define MAP_VIOLET_CITY 5
#define VIOLET_CITY_WIDTH 20
#define VIOLET_CITY_HEIGHT 18

#define GROUP_VIOLET_MART 10
#define MAP_VIOLET_MART 6
#define VIOLET_MART_WIDTH 6
#define VIOLET_MART_HEIGHT 4

#define GROUP_VIOLET_GYM 10
#define MAP_VIOLET_GYM 7
#define VIOLET_GYM_WIDTH 5
#define VIOLET_GYM_HEIGHT 8

#define GROUP_EARLS_POKEMON_ACADEMY 10
#define MAP_EARLS_POKEMON_ACADEMY 8
#define EARLS_POKEMON_ACADEMY_WIDTH 4
#define EARLS_POKEMON_ACADEMY_HEIGHT 8

#define GROUP_VIOLET_NICKNAME_SPEECH_HOUSE 10
#define MAP_VIOLET_NICKNAME_SPEECH_HOUSE 9
#define VIOLET_NICKNAME_SPEECH_HOUSE_WIDTH 4
#define VIOLET_NICKNAME_SPEECH_HOUSE_HEIGHT 4

#define GROUP_VIOLET_POKECENTER_1F 10
#define MAP_VIOLET_POKECENTER_1F 10
#define VIOLET_POKECENTER_1F_WIDTH 5
#define VIOLET_POKECENTER_1F_HEIGHT 4

#define GROUP_VIOLET_KYLES_HOUSE 10
#define MAP_VIOLET_KYLES_HOUSE 11
#define VIOLET_KYLES_HOUSE_WIDTH 4
#define VIOLET_KYLES_HOUSE_HEIGHT 4

#define GROUP_ROUTE_32_RUINS_OF_ALPH_GATE 10
#define MAP_ROUTE_32_RUINS_OF_ALPH_GATE 12
#define ROUTE_32_RUINS_OF_ALPH_GATE_WIDTH 5
#define ROUTE_32_RUINS_OF_ALPH_GATE_HEIGHT 4

#define GROUP_ROUTE_32_POKECENTER_1F 10
#define MAP_ROUTE_32_POKECENTER_1F 13
#define ROUTE_32_POKECENTER_1F_WIDTH 5
#define ROUTE_32_POKECENTER_1F_HEIGHT 4

#define GROUP_ROUTE_35_GOLDENROD_GATE 10
#define MAP_ROUTE_35_GOLDENROD_GATE 14
#define ROUTE_35_GOLDENROD_GATE_WIDTH 5
#define ROUTE_35_GOLDENROD_GATE_HEIGHT 4

#define GROUP_ROUTE_35_NATIONAL_PARK_GATE 10
#define MAP_ROUTE_35_NATIONAL_PARK_GATE 15
#define ROUTE_35_NATIONAL_PARK_GATE_WIDTH 4
#define ROUTE_35_NATIONAL_PARK_GATE_HEIGHT 4

#define GROUP_ROUTE_36_RUINS_OF_ALPH_GATE 10
#define MAP_ROUTE_36_RUINS_OF_ALPH_GATE 16
#define ROUTE_36_RUINS_OF_ALPH_GATE_WIDTH 5
#define ROUTE_36_RUINS_OF_ALPH_GATE_HEIGHT 4

#define GROUP_ROUTE_36_NATIONAL_PARK_GATE 10
#define MAP_ROUTE_36_NATIONAL_PARK_GATE 17
#define ROUTE_36_NATIONAL_PARK_GATE_WIDTH 5
#define ROUTE_36_NATIONAL_PARK_GATE_HEIGHT 4


#define MAPGROUP_GOLDENROD 11
#define GROUP_ROUTE_34 11
#define MAP_ROUTE_34 1
#define ROUTE_34_WIDTH 10
#define ROUTE_34_HEIGHT 27

#define GROUP_GOLDENROD_CITY 11
#define MAP_GOLDENROD_CITY 2
#define GOLDENROD_CITY_WIDTH 20
#define GOLDENROD_CITY_HEIGHT 18

#define GROUP_GOLDENROD_GYM 11
#define MAP_GOLDENROD_GYM 3
#define GOLDENROD_GYM_WIDTH 10
#define GOLDENROD_GYM_HEIGHT 9

#define GROUP_GOLDENROD_BIKE_SHOP 11
#define MAP_GOLDENROD_BIKE_SHOP 4
#define GOLDENROD_BIKE_SHOP_WIDTH 4
#define GOLDENROD_BIKE_SHOP_HEIGHT 4

#define GROUP_GOLDENROD_HAPPINESS_RATER 11
#define MAP_GOLDENROD_HAPPINESS_RATER 5
#define GOLDENROD_HAPPINESS_RATER_WIDTH 4
#define GOLDENROD_HAPPINESS_RATER_HEIGHT 4

#define GROUP_BILLS_FAMILYS_HOUSE 11
#define MAP_BILLS_FAMILYS_HOUSE 6
#define BILLS_FAMILYS_HOUSE_WIDTH 4
#define BILLS_FAMILYS_HOUSE_HEIGHT 4

#define GROUP_GOLDENROD_MAGNET_TRAIN_STATION 11
#define MAP_GOLDENROD_MAGNET_TRAIN_STATION 7
#define GOLDENROD_MAGNET_TRAIN_STATION_WIDTH 10
#define GOLDENROD_MAGNET_TRAIN_STATION_HEIGHT 9

#define GROUP_GOLDENROD_FLOWER_SHOP 11
#define MAP_GOLDENROD_FLOWER_SHOP 8
#define GOLDENROD_FLOWER_SHOP_WIDTH 4
#define GOLDENROD_FLOWER_SHOP_HEIGHT 4

#define GROUP_GOLDENROD_POKECENTER_1F 11
#define MAP_GOLDENROD_POKECENTER_1F 9
#define GOLDENROD_POKECENTER_1F_WIDTH 5
#define GOLDENROD_POKECENTER_1F_HEIGHT 4

#define GROUP_GOLDENROD_PP_SPEECH_HOUSE 11
#define MAP_GOLDENROD_PP_SPEECH_HOUSE 10
#define GOLDENROD_PP_SPEECH_HOUSE_WIDTH 4
#define GOLDENROD_PP_SPEECH_HOUSE_HEIGHT 4

#define GROUP_GOLDENROD_NAME_RATER 11
#define MAP_GOLDENROD_NAME_RATER 11
#define GOLDENROD_NAME_RATER_WIDTH 4
#define GOLDENROD_NAME_RATER_HEIGHT 4

#define GROUP_GOLDENROD_DEPT_STORE_1F 11
#define MAP_GOLDENROD_DEPT_STORE_1F 12
#define GOLDENROD_DEPT_STORE_1F_WIDTH 8
#define GOLDENROD_DEPT_STORE_1F_HEIGHT 4

#define GROUP_GOLDENROD_DEPT_STORE_2F 11
#define MAP_GOLDENROD_DEPT_STORE_2F 13
#define GOLDENROD_DEPT_STORE_2F_WIDTH 8
#define GOLDENROD_DEPT_STORE_2F_HEIGHT 4

#define GROUP_GOLDENROD_DEPT_STORE_3F 11
#define MAP_GOLDENROD_DEPT_STORE_3F 14
#define GOLDENROD_DEPT_STORE_3F_WIDTH 8
#define GOLDENROD_DEPT_STORE_3F_HEIGHT 4

#define GROUP_GOLDENROD_DEPT_STORE_4F 11
#define MAP_GOLDENROD_DEPT_STORE_4F 15
#define GOLDENROD_DEPT_STORE_4F_WIDTH 8
#define GOLDENROD_DEPT_STORE_4F_HEIGHT 4

#define GROUP_GOLDENROD_DEPT_STORE_5F 11
#define MAP_GOLDENROD_DEPT_STORE_5F 16
#define GOLDENROD_DEPT_STORE_5F_WIDTH 8
#define GOLDENROD_DEPT_STORE_5F_HEIGHT 4

#define GROUP_GOLDENROD_DEPT_STORE_6F 11
#define MAP_GOLDENROD_DEPT_STORE_6F 17
#define GOLDENROD_DEPT_STORE_6F_WIDTH 8
#define GOLDENROD_DEPT_STORE_6F_HEIGHT 4

#define GROUP_GOLDENROD_DEPT_STORE_ELEVATOR 11
#define MAP_GOLDENROD_DEPT_STORE_ELEVATOR 18
#define GOLDENROD_DEPT_STORE_ELEVATOR_WIDTH 2
#define GOLDENROD_DEPT_STORE_ELEVATOR_HEIGHT 2

#define GROUP_GOLDENROD_GAME_CORNER 11
#define MAP_GOLDENROD_GAME_CORNER 19
#define GOLDENROD_GAME_CORNER_WIDTH 10
#define GOLDENROD_GAME_CORNER_HEIGHT 7

#define GROUP_ILEX_FOREST_AZALEA_GATE 11
#define MAP_ILEX_FOREST_AZALEA_GATE 20
#define ILEX_FOREST_AZALEA_GATE_WIDTH 5
#define ILEX_FOREST_AZALEA_GATE_HEIGHT 4

#define GROUP_ROUTE_34_ILEX_FOREST_GATE 11
#define MAP_ROUTE_34_ILEX_FOREST_GATE 21
#define ROUTE_34_ILEX_FOREST_GATE_WIDTH 5
#define ROUTE_34_ILEX_FOREST_GATE_HEIGHT 4

#define GROUP_DAY_CARE 11
#define MAP_DAY_CARE 22
#define DAY_CARE_WIDTH 5
#define DAY_CARE_HEIGHT 4


#define MAPGROUP_VERMILION 12
#define GROUP_ROUTE_6 12
#define MAP_ROUTE_6 1
#define ROUTE_6_WIDTH 10
#define ROUTE_6_HEIGHT 9

#define GROUP_ROUTE_11 12
#define MAP_ROUTE_11 2
#define ROUTE_11_WIDTH 20
#define ROUTE_11_HEIGHT 9

#define GROUP_VERMILION_CITY 12
#define MAP_VERMILION_CITY 3
#define VERMILION_CITY_WIDTH 20
#define VERMILION_CITY_HEIGHT 18

#define GROUP_VERMILION_FISHING_SPEECH_HOUSE 12
#define MAP_VERMILION_FISHING_SPEECH_HOUSE 4
#define VERMILION_FISHING_SPEECH_HOUSE_WIDTH 4
#define VERMILION_FISHING_SPEECH_HOUSE_HEIGHT 4

#define GROUP_VERMILION_POKECENTER_1F 12
#define MAP_VERMILION_POKECENTER_1F 5
#define VERMILION_POKECENTER_1F_WIDTH 5
#define VERMILION_POKECENTER_1F_HEIGHT 4

#define GROUP_VERMILION_POKECENTER_2F_BETA 12
#define MAP_VERMILION_POKECENTER_2F_BETA 6
#define VERMILION_POKECENTER_2F_BETA_WIDTH 8
#define VERMILION_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_POKEMON_FAN_CLUB 12
#define MAP_POKEMON_FAN_CLUB 7
#define POKEMON_FAN_CLUB_WIDTH 5
#define POKEMON_FAN_CLUB_HEIGHT 4

#define GROUP_VERMILION_MAGNET_TRAIN_SPEECH_HOUSE 12
#define MAP_VERMILION_MAGNET_TRAIN_SPEECH_HOUSE 8
#define VERMILION_MAGNET_TRAIN_SPEECH_HOUSE_WIDTH 4
#define VERMILION_MAGNET_TRAIN_SPEECH_HOUSE_HEIGHT 4

#define GROUP_VERMILION_MART 12
#define MAP_VERMILION_MART 9
#define VERMILION_MART_WIDTH 6
#define VERMILION_MART_HEIGHT 4

#define GROUP_VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE 12
#define MAP_VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE 10
#define VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE_WIDTH 4
#define VERMILION_DIGLETTS_CAVE_SPEECH_HOUSE_HEIGHT 4

#define GROUP_VERMILION_GYM 12
#define MAP_VERMILION_GYM 11
#define VERMILION_GYM_WIDTH 5
#define VERMILION_GYM_HEIGHT 9

#define GROUP_ROUTE_6_SAFFRON_GATE 12
#define MAP_ROUTE_6_SAFFRON_GATE 12
#define ROUTE_6_SAFFRON_GATE_WIDTH 5
#define ROUTE_6_SAFFRON_GATE_HEIGHT 4

#define GROUP_ROUTE_6_UNDERGROUND_PATH_ENTRANCE 12
#define MAP_ROUTE_6_UNDERGROUND_PATH_ENTRANCE 13
#define ROUTE_6_UNDERGROUND_PATH_ENTRANCE_WIDTH 4
#define ROUTE_6_UNDERGROUND_PATH_ENTRANCE_HEIGHT 4


#define MAPGROUP_PALLET 13
#define GROUP_ROUTE_1 13
#define MAP_ROUTE_1 1
#define ROUTE_1_WIDTH 10
#define ROUTE_1_HEIGHT 18

#define GROUP_PALLET_TOWN 13
#define MAP_PALLET_TOWN 2
#define PALLET_TOWN_WIDTH 10
#define PALLET_TOWN_HEIGHT 9

#define GROUP_REDS_HOUSE_1F 13
#define MAP_REDS_HOUSE_1F 3
#define REDS_HOUSE_1F_WIDTH 4
#define REDS_HOUSE_1F_HEIGHT 4

#define GROUP_REDS_HOUSE_2F 13
#define MAP_REDS_HOUSE_2F 4
#define REDS_HOUSE_2F_WIDTH 4
#define REDS_HOUSE_2F_HEIGHT 4

#define GROUP_BLUES_HOUSE 13
#define MAP_BLUES_HOUSE 5
#define BLUES_HOUSE_WIDTH 4
#define BLUES_HOUSE_HEIGHT 4

#define GROUP_OAKS_LAB 13
#define MAP_OAKS_LAB 6
#define OAKS_LAB_WIDTH 5
#define OAKS_LAB_HEIGHT 6


#define MAPGROUP_PEWTER 14
#define GROUP_ROUTE_3 14
#define MAP_ROUTE_3 1
#define ROUTE_3_WIDTH 30
#define ROUTE_3_HEIGHT 9

#define GROUP_PEWTER_CITY 14
#define MAP_PEWTER_CITY 2
#define PEWTER_CITY_WIDTH 20
#define PEWTER_CITY_HEIGHT 18

#define GROUP_PEWTER_NIDORAN_SPEECH_HOUSE 14
#define MAP_PEWTER_NIDORAN_SPEECH_HOUSE 3
#define PEWTER_NIDORAN_SPEECH_HOUSE_WIDTH 4
#define PEWTER_NIDORAN_SPEECH_HOUSE_HEIGHT 4

#define GROUP_PEWTER_GYM 14
#define MAP_PEWTER_GYM 4
#define PEWTER_GYM_WIDTH 5
#define PEWTER_GYM_HEIGHT 7

#define GROUP_PEWTER_MART 14
#define MAP_PEWTER_MART 5
#define PEWTER_MART_WIDTH 6
#define PEWTER_MART_HEIGHT 4

#define GROUP_PEWTER_POKECENTER_1F 14
#define MAP_PEWTER_POKECENTER_1F 6
#define PEWTER_POKECENTER_1F_WIDTH 5
#define PEWTER_POKECENTER_1F_HEIGHT 4

#define GROUP_PEWTER_POKECENTER_2F_BETA 14
#define MAP_PEWTER_POKECENTER_2F_BETA 7
#define PEWTER_POKECENTER_2F_BETA_WIDTH 8
#define PEWTER_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_PEWTER_SNOOZE_SPEECH_HOUSE 14
#define MAP_PEWTER_SNOOZE_SPEECH_HOUSE 8
#define PEWTER_SNOOZE_SPEECH_HOUSE_WIDTH 4
#define PEWTER_SNOOZE_SPEECH_HOUSE_HEIGHT 4


#define MAPGROUP_FAST_SHIP 15
#define GROUP_OLIVINE_PORT 15
#define MAP_OLIVINE_PORT 1
#define OLIVINE_PORT_WIDTH 10
#define OLIVINE_PORT_HEIGHT 18

#define GROUP_VERMILION_PORT 15
#define MAP_VERMILION_PORT 2
#define VERMILION_PORT_WIDTH 10
#define VERMILION_PORT_HEIGHT 18

#define GROUP_FAST_SHIP_1F 15
#define MAP_FAST_SHIP_1F 3
#define FAST_SHIP_1F_WIDTH 16
#define FAST_SHIP_1F_HEIGHT 9

#define GROUP_FAST_SHIP_CABINS_NNW_NNE_NE 15
#define MAP_FAST_SHIP_CABINS_NNW_NNE_NE 4
#define FAST_SHIP_CABINS_NNW_NNE_NE_WIDTH 4
#define FAST_SHIP_CABINS_NNW_NNE_NE_HEIGHT 16

#define GROUP_FAST_SHIP_CABINS_SW_SSW_NW 15
#define MAP_FAST_SHIP_CABINS_SW_SSW_NW 5
#define FAST_SHIP_CABINS_SW_SSW_NW_WIDTH 4
#define FAST_SHIP_CABINS_SW_SSW_NW_HEIGHT 16

#define GROUP_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN 15
#define MAP_FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN 6
#define FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_WIDTH 5
#define FAST_SHIP_CABINS_SE_SSE_CAPTAINS_CABIN_HEIGHT 17

#define GROUP_FAST_SHIP_B1F 15
#define MAP_FAST_SHIP_B1F 7
#define FAST_SHIP_B1F_WIDTH 16
#define FAST_SHIP_B1F_HEIGHT 8

#define GROUP_OLIVINE_PORT_PASSAGE 15
#define MAP_OLIVINE_PORT_PASSAGE 8
#define OLIVINE_PORT_PASSAGE_WIDTH 10
#define OLIVINE_PORT_PASSAGE_HEIGHT 9

#define GROUP_VERMILION_PORT_PASSAGE 15
#define MAP_VERMILION_PORT_PASSAGE 9
#define VERMILION_PORT_PASSAGE_WIDTH 10
#define VERMILION_PORT_PASSAGE_HEIGHT 9

#define GROUP_MOUNT_MOON_SQUARE 15
#define MAP_MOUNT_MOON_SQUARE 10
#define MOUNT_MOON_SQUARE_WIDTH 15
#define MOUNT_MOON_SQUARE_HEIGHT 9

#define GROUP_MOUNT_MOON_GIFT_SHOP 15
#define MAP_MOUNT_MOON_GIFT_SHOP 11
#define MOUNT_MOON_GIFT_SHOP_WIDTH 4
#define MOUNT_MOON_GIFT_SHOP_HEIGHT 4

#define GROUP_TIN_TOWER_ROOF 15
#define MAP_TIN_TOWER_ROOF 12
#define TIN_TOWER_ROOF_WIDTH 10
#define TIN_TOWER_ROOF_HEIGHT 9


#define MAPGROUP_INDIGO 16
#define GROUP_ROUTE_23 16
#define MAP_ROUTE_23 1
#define ROUTE_23_WIDTH 10
#define ROUTE_23_HEIGHT 9

#define GROUP_INDIGO_PLATEAU_POKECENTER_1F 16
#define MAP_INDIGO_PLATEAU_POKECENTER_1F 2
#define INDIGO_PLATEAU_POKECENTER_1F_WIDTH 9
#define INDIGO_PLATEAU_POKECENTER_1F_HEIGHT 7

#define GROUP_WILLS_ROOM 16
#define MAP_WILLS_ROOM 3
#define WILLS_ROOM_WIDTH 5
#define WILLS_ROOM_HEIGHT 9

#define GROUP_KOGAS_ROOM 16
#define MAP_KOGAS_ROOM 4
#define KOGAS_ROOM_WIDTH 5
#define KOGAS_ROOM_HEIGHT 9

#define GROUP_BRUNOS_ROOM 16
#define MAP_BRUNOS_ROOM 5
#define BRUNOS_ROOM_WIDTH 5
#define BRUNOS_ROOM_HEIGHT 9

#define GROUP_KARENS_ROOM 16
#define MAP_KARENS_ROOM 6
#define KARENS_ROOM_WIDTH 5
#define KARENS_ROOM_HEIGHT 9

#define GROUP_LANCES_ROOM 16
#define MAP_LANCES_ROOM 7
#define LANCES_ROOM_WIDTH 5
#define LANCES_ROOM_HEIGHT 12

#define GROUP_HALL_OF_FAME 16
#define MAP_HALL_OF_FAME 8
#define HALL_OF_FAME_WIDTH 5
#define HALL_OF_FAME_HEIGHT 7


#define MAPGROUP_FUCHSIA 17
#define GROUP_ROUTE_13 17
#define MAP_ROUTE_13 1
#define ROUTE_13_WIDTH 30
#define ROUTE_13_HEIGHT 9

#define GROUP_ROUTE_14 17
#define MAP_ROUTE_14 2
#define ROUTE_14_WIDTH 10
#define ROUTE_14_HEIGHT 18

#define GROUP_ROUTE_15 17
#define MAP_ROUTE_15 3
#define ROUTE_15_WIDTH 20
#define ROUTE_15_HEIGHT 9

#define GROUP_ROUTE_18 17
#define MAP_ROUTE_18 4
#define ROUTE_18_WIDTH 10
#define ROUTE_18_HEIGHT 9

#define GROUP_FUCHSIA_CITY 17
#define MAP_FUCHSIA_CITY 5
#define FUCHSIA_CITY_WIDTH 20
#define FUCHSIA_CITY_HEIGHT 18

#define GROUP_FUCHSIA_MART 17
#define MAP_FUCHSIA_MART 6
#define FUCHSIA_MART_WIDTH 6
#define FUCHSIA_MART_HEIGHT 4

#define GROUP_SAFARI_ZONE_MAIN_OFFICE 17
#define MAP_SAFARI_ZONE_MAIN_OFFICE 7
#define SAFARI_ZONE_MAIN_OFFICE_WIDTH 4
#define SAFARI_ZONE_MAIN_OFFICE_HEIGHT 4

#define GROUP_FUCHSIA_GYM 17
#define MAP_FUCHSIA_GYM 8
#define FUCHSIA_GYM_WIDTH 5
#define FUCHSIA_GYM_HEIGHT 9

#define GROUP_BILLS_BROTHERS_HOUSE 17
#define MAP_BILLS_BROTHERS_HOUSE 9
#define BILLS_BROTHERS_HOUSE_WIDTH 4
#define BILLS_BROTHERS_HOUSE_HEIGHT 4

#define GROUP_FUCHSIA_POKECENTER_1F 17
#define MAP_FUCHSIA_POKECENTER_1F 10
#define FUCHSIA_POKECENTER_1F_WIDTH 5
#define FUCHSIA_POKECENTER_1F_HEIGHT 4

#define GROUP_FUCHSIA_POKECENTER_2F_BETA 17
#define MAP_FUCHSIA_POKECENTER_2F_BETA 11
#define FUCHSIA_POKECENTER_2F_BETA_WIDTH 8
#define FUCHSIA_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_SAFARI_ZONE_WARDENS_HOME 17
#define MAP_SAFARI_ZONE_WARDENS_HOME 12
#define SAFARI_ZONE_WARDENS_HOME_WIDTH 5
#define SAFARI_ZONE_WARDENS_HOME_HEIGHT 4

#define GROUP_ROUTE_15_FUCHSIA_GATE 17
#define MAP_ROUTE_15_FUCHSIA_GATE 13
#define ROUTE_15_FUCHSIA_GATE_WIDTH 5
#define ROUTE_15_FUCHSIA_GATE_HEIGHT 4


#define MAPGROUP_LAVENDER 18
#define GROUP_ROUTE_8 18
#define MAP_ROUTE_8 1
#define ROUTE_8_WIDTH 20
#define ROUTE_8_HEIGHT 9

#define GROUP_ROUTE_12 18
#define MAP_ROUTE_12 2
#define ROUTE_12_WIDTH 10
#define ROUTE_12_HEIGHT 27

#define GROUP_ROUTE_10_SOUTH 18
#define MAP_ROUTE_10_SOUTH 3
#define ROUTE_10_SOUTH_WIDTH 10
#define ROUTE_10_SOUTH_HEIGHT 9

#define GROUP_LAVENDER_TOWN 18
#define MAP_LAVENDER_TOWN 4
#define LAVENDER_TOWN_WIDTH 10
#define LAVENDER_TOWN_HEIGHT 9

#define GROUP_LAVENDER_POKECENTER_1F 18
#define MAP_LAVENDER_POKECENTER_1F 5
#define LAVENDER_POKECENTER_1F_WIDTH 5
#define LAVENDER_POKECENTER_1F_HEIGHT 4

#define GROUP_LAVENDER_POKECENTER_2F_BETA 18
#define MAP_LAVENDER_POKECENTER_2F_BETA 6
#define LAVENDER_POKECENTER_2F_BETA_WIDTH 8
#define LAVENDER_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_MR_FUJIS_HOUSE 18
#define MAP_MR_FUJIS_HOUSE 7
#define MR_FUJIS_HOUSE_WIDTH 5
#define MR_FUJIS_HOUSE_HEIGHT 4

#define GROUP_LAVENDER_SPEECH_HOUSE 18
#define MAP_LAVENDER_SPEECH_HOUSE 8
#define LAVENDER_SPEECH_HOUSE_WIDTH 4
#define LAVENDER_SPEECH_HOUSE_HEIGHT 4

#define GROUP_LAVENDER_NAME_RATER 18
#define MAP_LAVENDER_NAME_RATER 9
#define LAVENDER_NAME_RATER_WIDTH 4
#define LAVENDER_NAME_RATER_HEIGHT 4

#define GROUP_LAVENDER_MART 18
#define MAP_LAVENDER_MART 10
#define LAVENDER_MART_WIDTH 6
#define LAVENDER_MART_HEIGHT 4

#define GROUP_SOUL_HOUSE 18
#define MAP_SOUL_HOUSE 11
#define SOUL_HOUSE_WIDTH 5
#define SOUL_HOUSE_HEIGHT 4

#define GROUP_LAV_RADIO_TOWER_1F 18
#define MAP_LAV_RADIO_TOWER_1F 12
#define LAV_RADIO_TOWER_1F_WIDTH 10
#define LAV_RADIO_TOWER_1F_HEIGHT 4

#define GROUP_ROUTE_8_SAFFRON_GATE 18
#define MAP_ROUTE_8_SAFFRON_GATE 13
#define ROUTE_8_SAFFRON_GATE_WIDTH 5
#define ROUTE_8_SAFFRON_GATE_HEIGHT 4

#define GROUP_ROUTE_12_SUPER_ROD_HOUSE 18
#define MAP_ROUTE_12_SUPER_ROD_HOUSE 14
#define ROUTE_12_SUPER_ROD_HOUSE_WIDTH 4
#define ROUTE_12_SUPER_ROD_HOUSE_HEIGHT 4


#define MAPGROUP_SILVER 19
#define GROUP_ROUTE_28 19
#define MAP_ROUTE_28 1
#define ROUTE_28_WIDTH 20
#define ROUTE_28_HEIGHT 9

#define GROUP_SILVER_CAVE_OUTSIDE 19
#define MAP_SILVER_CAVE_OUTSIDE 2
#define SILVER_CAVE_OUTSIDE_WIDTH 20
#define SILVER_CAVE_OUTSIDE_HEIGHT 18

#define GROUP_SILVER_CAVE_POKECENTER_1F 19
#define MAP_SILVER_CAVE_POKECENTER_1F 3
#define SILVER_CAVE_POKECENTER_1F_WIDTH 5
#define SILVER_CAVE_POKECENTER_1F_HEIGHT 4

#define GROUP_ROUTE_28_STEEL_WING_HOUSE 19
#define MAP_ROUTE_28_STEEL_WING_HOUSE 4
#define ROUTE_28_STEEL_WING_HOUSE_WIDTH 4
#define ROUTE_28_STEEL_WING_HOUSE_HEIGHT 4


#define MAPGROUP_CABLE_CLUB 20
#define GROUP_POKECENTER_2F 20
#define MAP_POKECENTER_2F 1
#define POKECENTER_2F_WIDTH 8
#define POKECENTER_2F_HEIGHT 4

#define GROUP_TRADE_CENTER 20
#define MAP_TRADE_CENTER 2
#define TRADE_CENTER_WIDTH 5
#define TRADE_CENTER_HEIGHT 4

#define GROUP_COLOSSEUM 20
#define MAP_COLOSSEUM 3
#define COLOSSEUM_WIDTH 5
#define COLOSSEUM_HEIGHT 4

#define GROUP_TIME_CAPSULE 20
#define MAP_TIME_CAPSULE 4
#define TIME_CAPSULE_WIDTH 5
#define TIME_CAPSULE_HEIGHT 4


#define MAPGROUP_CELADON 21
#define GROUP_ROUTE_7 21
#define MAP_ROUTE_7 1
#define ROUTE_7_WIDTH 10
#define ROUTE_7_HEIGHT 9

#define GROUP_ROUTE_16 21
#define MAP_ROUTE_16 2
#define ROUTE_16_WIDTH 10
#define ROUTE_16_HEIGHT 9

#define GROUP_ROUTE_17 21
#define MAP_ROUTE_17 3
#define ROUTE_17_WIDTH 10
#define ROUTE_17_HEIGHT 45

#define GROUP_CELADON_CITY 21
#define MAP_CELADON_CITY 4
#define CELADON_CITY_WIDTH 20
#define CELADON_CITY_HEIGHT 18

#define GROUP_CELADON_DEPT_STORE_1F 21
#define MAP_CELADON_DEPT_STORE_1F 5
#define CELADON_DEPT_STORE_1F_WIDTH 8
#define CELADON_DEPT_STORE_1F_HEIGHT 4

#define GROUP_CELADON_DEPT_STORE_2F 21
#define MAP_CELADON_DEPT_STORE_2F 6
#define CELADON_DEPT_STORE_2F_WIDTH 8
#define CELADON_DEPT_STORE_2F_HEIGHT 4

#define GROUP_CELADON_DEPT_STORE_3F 21
#define MAP_CELADON_DEPT_STORE_3F 7
#define CELADON_DEPT_STORE_3F_WIDTH 8
#define CELADON_DEPT_STORE_3F_HEIGHT 4

#define GROUP_CELADON_DEPT_STORE_4F 21
#define MAP_CELADON_DEPT_STORE_4F 8
#define CELADON_DEPT_STORE_4F_WIDTH 8
#define CELADON_DEPT_STORE_4F_HEIGHT 4

#define GROUP_CELADON_DEPT_STORE_5F 21
#define MAP_CELADON_DEPT_STORE_5F 9
#define CELADON_DEPT_STORE_5F_WIDTH 8
#define CELADON_DEPT_STORE_5F_HEIGHT 4

#define GROUP_CELADON_DEPT_STORE_6F 21
#define MAP_CELADON_DEPT_STORE_6F 10
#define CELADON_DEPT_STORE_6F_WIDTH 8
#define CELADON_DEPT_STORE_6F_HEIGHT 4

#define GROUP_CELADON_DEPT_STORE_ELEVATOR 21
#define MAP_CELADON_DEPT_STORE_ELEVATOR 11
#define CELADON_DEPT_STORE_ELEVATOR_WIDTH 2
#define CELADON_DEPT_STORE_ELEVATOR_HEIGHT 2

#define GROUP_CELADON_MANSION_1F 21
#define MAP_CELADON_MANSION_1F 12
#define CELADON_MANSION_1F_WIDTH 4
#define CELADON_MANSION_1F_HEIGHT 5

#define GROUP_CELADON_MANSION_2F 21
#define MAP_CELADON_MANSION_2F 13
#define CELADON_MANSION_2F_WIDTH 4
#define CELADON_MANSION_2F_HEIGHT 5

#define GROUP_CELADON_MANSION_3F 21
#define MAP_CELADON_MANSION_3F 14
#define CELADON_MANSION_3F_WIDTH 4
#define CELADON_MANSION_3F_HEIGHT 5

#define GROUP_CELADON_MANSION_ROOF 21
#define MAP_CELADON_MANSION_ROOF 15
#define CELADON_MANSION_ROOF_WIDTH 4
#define CELADON_MANSION_ROOF_HEIGHT 5

#define GROUP_CELADON_MANSION_ROOF_HOUSE 21
#define MAP_CELADON_MANSION_ROOF_HOUSE 16
#define CELADON_MANSION_ROOF_HOUSE_WIDTH 4
#define CELADON_MANSION_ROOF_HOUSE_HEIGHT 4

#define GROUP_CELADON_POKECENTER_1F 21
#define MAP_CELADON_POKECENTER_1F 17
#define CELADON_POKECENTER_1F_WIDTH 5
#define CELADON_POKECENTER_1F_HEIGHT 4

#define GROUP_CELADON_POKECENTER_2F_BETA 21
#define MAP_CELADON_POKECENTER_2F_BETA 18
#define CELADON_POKECENTER_2F_BETA_WIDTH 8
#define CELADON_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_CELADON_GAME_CORNER 21
#define MAP_CELADON_GAME_CORNER 19
#define CELADON_GAME_CORNER_WIDTH 10
#define CELADON_GAME_CORNER_HEIGHT 7

#define GROUP_CELADON_GAME_CORNER_PRIZE_ROOM 21
#define MAP_CELADON_GAME_CORNER_PRIZE_ROOM 20
#define CELADON_GAME_CORNER_PRIZE_ROOM_WIDTH 3
#define CELADON_GAME_CORNER_PRIZE_ROOM_HEIGHT 3

#define GROUP_CELADON_GYM 21
#define MAP_CELADON_GYM 21
#define CELADON_GYM_WIDTH 5
#define CELADON_GYM_HEIGHT 9

#define GROUP_CELADON_CAFE 21
#define MAP_CELADON_CAFE 22
#define CELADON_CAFE_WIDTH 6
#define CELADON_CAFE_HEIGHT 4

#define GROUP_ROUTE_16_FUCHSIA_SPEECH_HOUSE 21
#define MAP_ROUTE_16_FUCHSIA_SPEECH_HOUSE 23
#define ROUTE_16_FUCHSIA_SPEECH_HOUSE_WIDTH 4
#define ROUTE_16_FUCHSIA_SPEECH_HOUSE_HEIGHT 4

#define GROUP_ROUTE_16_GATE 21
#define MAP_ROUTE_16_GATE 24
#define ROUTE_16_GATE_WIDTH 5
#define ROUTE_16_GATE_HEIGHT 4

#define GROUP_ROUTE_7_SAFFRON_GATE 21
#define MAP_ROUTE_7_SAFFRON_GATE 25
#define ROUTE_7_SAFFRON_GATE_WIDTH 5
#define ROUTE_7_SAFFRON_GATE_HEIGHT 4

#define GROUP_ROUTE_17_ROUTE_18_GATE 21
#define MAP_ROUTE_17_ROUTE_18_GATE 26
#define ROUTE_17_ROUTE_18_GATE_WIDTH 5
#define ROUTE_17_ROUTE_18_GATE_HEIGHT 4


#define MAPGROUP_CIANWOOD 22
#define GROUP_ROUTE_40 22
#define MAP_ROUTE_40 1
#define ROUTE_40_WIDTH 10
#define ROUTE_40_HEIGHT 18

#define GROUP_ROUTE_41 22
#define MAP_ROUTE_41 2
#define ROUTE_41_WIDTH 25
#define ROUTE_41_HEIGHT 27

#define GROUP_CIANWOOD_CITY 22
#define MAP_CIANWOOD_CITY 3
#define CIANWOOD_CITY_WIDTH 15
#define CIANWOOD_CITY_HEIGHT 27

#define GROUP_MANIAS_HOUSE 22
#define MAP_MANIAS_HOUSE 4
#define MANIAS_HOUSE_WIDTH 4
#define MANIAS_HOUSE_HEIGHT 4

#define GROUP_CIANWOOD_GYM 22
#define MAP_CIANWOOD_GYM 5
#define CIANWOOD_GYM_WIDTH 5
#define CIANWOOD_GYM_HEIGHT 9

#define GROUP_CIANWOOD_POKECENTER_1F 22
#define MAP_CIANWOOD_POKECENTER_1F 6
#define CIANWOOD_POKECENTER_1F_WIDTH 5
#define CIANWOOD_POKECENTER_1F_HEIGHT 4

#define GROUP_CIANWOOD_PHARMACY 22
#define MAP_CIANWOOD_PHARMACY 7
#define CIANWOOD_PHARMACY_WIDTH 4
#define CIANWOOD_PHARMACY_HEIGHT 4

#define GROUP_CIANWOOD_PHOTO_STUDIO 22
#define MAP_CIANWOOD_PHOTO_STUDIO 8
#define CIANWOOD_PHOTO_STUDIO_WIDTH 4
#define CIANWOOD_PHOTO_STUDIO_HEIGHT 4

#define GROUP_CIANWOOD_LUGIA_SPEECH_HOUSE 22
#define MAP_CIANWOOD_LUGIA_SPEECH_HOUSE 9
#define CIANWOOD_LUGIA_SPEECH_HOUSE_WIDTH 4
#define CIANWOOD_LUGIA_SPEECH_HOUSE_HEIGHT 4


#define MAPGROUP_VIRIDIAN 23
#define GROUP_ROUTE_2 23
#define MAP_ROUTE_2 1
#define ROUTE_2_WIDTH 10
#define ROUTE_2_HEIGHT 27

#define GROUP_ROUTE_22 23
#define MAP_ROUTE_22 2
#define ROUTE_22_WIDTH 20
#define ROUTE_22_HEIGHT 9

#define GROUP_VIRIDIAN_CITY 23
#define MAP_VIRIDIAN_CITY 3
#define VIRIDIAN_CITY_WIDTH 20
#define VIRIDIAN_CITY_HEIGHT 18

#define GROUP_VIRIDIAN_GYM 23
#define MAP_VIRIDIAN_GYM 4
#define VIRIDIAN_GYM_WIDTH 5
#define VIRIDIAN_GYM_HEIGHT 9

#define GROUP_VIRIDIAN_NICKNAME_SPEECH_HOUSE 23
#define MAP_VIRIDIAN_NICKNAME_SPEECH_HOUSE 5
#define VIRIDIAN_NICKNAME_SPEECH_HOUSE_WIDTH 4
#define VIRIDIAN_NICKNAME_SPEECH_HOUSE_HEIGHT 4

#define GROUP_TRAINER_HOUSE_1F 23
#define MAP_TRAINER_HOUSE_1F 6
#define TRAINER_HOUSE_1F_WIDTH 5
#define TRAINER_HOUSE_1F_HEIGHT 7

#define GROUP_TRAINER_HOUSE_B1F 23
#define MAP_TRAINER_HOUSE_B1F 7
#define TRAINER_HOUSE_B1F_WIDTH 5
#define TRAINER_HOUSE_B1F_HEIGHT 8

#define GROUP_VIRIDIAN_MART 23
#define MAP_VIRIDIAN_MART 8
#define VIRIDIAN_MART_WIDTH 6
#define VIRIDIAN_MART_HEIGHT 4

#define GROUP_VIRIDIAN_POKECENTER_1F 23
#define MAP_VIRIDIAN_POKECENTER_1F 9
#define VIRIDIAN_POKECENTER_1F_WIDTH 5
#define VIRIDIAN_POKECENTER_1F_HEIGHT 4

#define GROUP_VIRIDIAN_POKECENTER_2F_BETA 23
#define MAP_VIRIDIAN_POKECENTER_2F_BETA 10
#define VIRIDIAN_POKECENTER_2F_BETA_WIDTH 8
#define VIRIDIAN_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_ROUTE_2_NUGGET_HOUSE 23
#define MAP_ROUTE_2_NUGGET_HOUSE 11
#define ROUTE_2_NUGGET_HOUSE_WIDTH 4
#define ROUTE_2_NUGGET_HOUSE_HEIGHT 4

#define GROUP_ROUTE_2_GATE 23
#define MAP_ROUTE_2_GATE 12
#define ROUTE_2_GATE_WIDTH 5
#define ROUTE_2_GATE_HEIGHT 4

#define GROUP_VICTORY_ROAD_GATE 23
#define MAP_VICTORY_ROAD_GATE 13
#define VICTORY_ROAD_GATE_WIDTH 10
#define VICTORY_ROAD_GATE_HEIGHT 9


#define MAPGROUP_NEW_BARK 24
#define GROUP_ROUTE_26 24
#define MAP_ROUTE_26 1
#define ROUTE_26_WIDTH 10
#define ROUTE_26_HEIGHT 54

#define GROUP_ROUTE_27 24
#define MAP_ROUTE_27 2
#define ROUTE_27_WIDTH 40
#define ROUTE_27_HEIGHT 9

#define GROUP_ROUTE_29 24
#define MAP_ROUTE_29 3
#define ROUTE_29_WIDTH 30
#define ROUTE_29_HEIGHT 9

#define GROUP_NEW_BARK_TOWN 24
#define MAP_NEW_BARK_TOWN 4
#define NEW_BARK_TOWN_WIDTH 10
#define NEW_BARK_TOWN_HEIGHT 9

#define GROUP_ELMS_LAB 24
#define MAP_ELMS_LAB 5
#define ELMS_LAB_WIDTH 5
#define ELMS_LAB_HEIGHT 6

#define GROUP_PLAYERS_HOUSE_1F 24
#define MAP_PLAYERS_HOUSE_1F 6
#define PLAYERS_HOUSE_1F_WIDTH 5
#define PLAYERS_HOUSE_1F_HEIGHT 4

#define GROUP_PLAYERS_HOUSE_2F 24
#define MAP_PLAYERS_HOUSE_2F 7
#define PLAYERS_HOUSE_2F_WIDTH 4
#define PLAYERS_HOUSE_2F_HEIGHT 3

#define GROUP_PLAYERS_NEIGHBORS_HOUSE 24
#define MAP_PLAYERS_NEIGHBORS_HOUSE 8
#define PLAYERS_NEIGHBORS_HOUSE_WIDTH 4
#define PLAYERS_NEIGHBORS_HOUSE_HEIGHT 4

#define GROUP_ELMS_HOUSE 24
#define MAP_ELMS_HOUSE 9
#define ELMS_HOUSE_WIDTH 4
#define ELMS_HOUSE_HEIGHT 4

#define GROUP_ROUTE_26_HEAL_HOUSE 24
#define MAP_ROUTE_26_HEAL_HOUSE 10
#define ROUTE_26_HEAL_HOUSE_WIDTH 4
#define ROUTE_26_HEAL_HOUSE_HEIGHT 4

#define GROUP_DAY_OF_WEEK_SIBLINGS_HOUSE 24
#define MAP_DAY_OF_WEEK_SIBLINGS_HOUSE 11
#define DAY_OF_WEEK_SIBLINGS_HOUSE_WIDTH 4
#define DAY_OF_WEEK_SIBLINGS_HOUSE_HEIGHT 4

#define GROUP_ROUTE_27_SANDSTORM_HOUSE 24
#define MAP_ROUTE_27_SANDSTORM_HOUSE 12
#define ROUTE_27_SANDSTORM_HOUSE_WIDTH 4
#define ROUTE_27_SANDSTORM_HOUSE_HEIGHT 4

#define GROUP_ROUTE_29_ROUTE_46_GATE 24
#define MAP_ROUTE_29_ROUTE_46_GATE 13
#define ROUTE_29_ROUTE_46_GATE_WIDTH 5
#define ROUTE_29_ROUTE_46_GATE_HEIGHT 4


#define MAPGROUP_SAFFRON 25
#define GROUP_ROUTE_5 25
#define MAP_ROUTE_5 1
#define ROUTE_5_WIDTH 10
#define ROUTE_5_HEIGHT 9

#define GROUP_SAFFRON_CITY 25
#define MAP_SAFFRON_CITY 2
#define SAFFRON_CITY_WIDTH 20
#define SAFFRON_CITY_HEIGHT 18

#define GROUP_FIGHTING_DOJO 25
#define MAP_FIGHTING_DOJO 3
#define FIGHTING_DOJO_WIDTH 5
#define FIGHTING_DOJO_HEIGHT 6

#define GROUP_SAFFRON_GYM 25
#define MAP_SAFFRON_GYM 4
#define SAFFRON_GYM_WIDTH 10
#define SAFFRON_GYM_HEIGHT 9

#define GROUP_SAFFRON_MART 25
#define MAP_SAFFRON_MART 5
#define SAFFRON_MART_WIDTH 6
#define SAFFRON_MART_HEIGHT 4

#define GROUP_SAFFRON_POKECENTER_1F 25
#define MAP_SAFFRON_POKECENTER_1F 6
#define SAFFRON_POKECENTER_1F_WIDTH 5
#define SAFFRON_POKECENTER_1F_HEIGHT 4

#define GROUP_SAFFRON_POKECENTER_2F_BETA 25
#define MAP_SAFFRON_POKECENTER_2F_BETA 7
#define SAFFRON_POKECENTER_2F_BETA_WIDTH 8
#define SAFFRON_POKECENTER_2F_BETA_HEIGHT 4

#define GROUP_MR_PSYCHICS_HOUSE 25
#define MAP_MR_PSYCHICS_HOUSE 8
#define MR_PSYCHICS_HOUSE_WIDTH 4
#define MR_PSYCHICS_HOUSE_HEIGHT 4

#define GROUP_SAFFRON_MAGNET_TRAIN_STATION 25
#define MAP_SAFFRON_MAGNET_TRAIN_STATION 9
#define SAFFRON_MAGNET_TRAIN_STATION_WIDTH 10
#define SAFFRON_MAGNET_TRAIN_STATION_HEIGHT 9

#define GROUP_SILPH_CO_1F 25
#define MAP_SILPH_CO_1F 10
#define SILPH_CO_1F_WIDTH 8
#define SILPH_CO_1F_HEIGHT 4

#define GROUP_COPYCATS_HOUSE_1F 25
#define MAP_COPYCATS_HOUSE_1F 11
#define COPYCATS_HOUSE_1F_WIDTH 4
#define COPYCATS_HOUSE_1F_HEIGHT 4

#define GROUP_COPYCATS_HOUSE_2F 25
#define MAP_COPYCATS_HOUSE_2F 12
#define COPYCATS_HOUSE_2F_WIDTH 5
#define COPYCATS_HOUSE_2F_HEIGHT 3

#define GROUP_ROUTE_5_UNDERGROUND_PATH_ENTRANCE 25
#define MAP_ROUTE_5_UNDERGROUND_PATH_ENTRANCE 13
#define ROUTE_5_UNDERGROUND_PATH_ENTRANCE_WIDTH 4
#define ROUTE_5_UNDERGROUND_PATH_ENTRANCE_HEIGHT 4

#define GROUP_ROUTE_5_SAFFRON_GATE 25
#define MAP_ROUTE_5_SAFFRON_GATE 14
#define ROUTE_5_SAFFRON_GATE_WIDTH 5
#define ROUTE_5_SAFFRON_GATE_HEIGHT 4

#define GROUP_ROUTE_5_CLEANSE_TAG_HOUSE 25
#define MAP_ROUTE_5_CLEANSE_TAG_HOUSE 15
#define ROUTE_5_CLEANSE_TAG_HOUSE_WIDTH 4
#define ROUTE_5_CLEANSE_TAG_HOUSE_HEIGHT 4


#define MAPGROUP_CHERRYGROVE 26
#define GROUP_ROUTE_30 26
#define MAP_ROUTE_30 1
#define ROUTE_30_WIDTH 10
#define ROUTE_30_HEIGHT 27

#define GROUP_ROUTE_31 26
#define MAP_ROUTE_31 2
#define ROUTE_31_WIDTH 20
#define ROUTE_31_HEIGHT 9

#define GROUP_CHERRYGROVE_CITY 26
#define MAP_CHERRYGROVE_CITY 3
#define CHERRYGROVE_CITY_WIDTH 20
#define CHERRYGROVE_CITY_HEIGHT 9

#define GROUP_CHERRYGROVE_MART 26
#define MAP_CHERRYGROVE_MART 4
#define CHERRYGROVE_MART_WIDTH 6
#define CHERRYGROVE_MART_HEIGHT 4

#define GROUP_CHERRYGROVE_POKECENTER_1F 26
#define MAP_CHERRYGROVE_POKECENTER_1F 5
#define CHERRYGROVE_POKECENTER_1F_WIDTH 5
#define CHERRYGROVE_POKECENTER_1F_HEIGHT 4

#define GROUP_CHERRYGROVE_GYM_SPEECH_HOUSE 26
#define MAP_CHERRYGROVE_GYM_SPEECH_HOUSE 6
#define CHERRYGROVE_GYM_SPEECH_HOUSE_WIDTH 4
#define CHERRYGROVE_GYM_SPEECH_HOUSE_HEIGHT 4

#define GROUP_GUIDE_GENTS_HOUSE 26
#define MAP_GUIDE_GENTS_HOUSE 7
#define GUIDE_GENTS_HOUSE_WIDTH 4
#define GUIDE_GENTS_HOUSE_HEIGHT 4

#define GROUP_CHERRYGROVE_EVOLUTION_SPEECH_HOUSE 26
#define MAP_CHERRYGROVE_EVOLUTION_SPEECH_HOUSE 8
#define CHERRYGROVE_EVOLUTION_SPEECH_HOUSE_WIDTH 4
#define CHERRYGROVE_EVOLUTION_SPEECH_HOUSE_HEIGHT 4

#define GROUP_ROUTE_30_BERRY_HOUSE 26
#define MAP_ROUTE_30_BERRY_HOUSE 9
#define ROUTE_30_BERRY_HOUSE_WIDTH 4
#define ROUTE_30_BERRY_HOUSE_HEIGHT 4

#define GROUP_MR_POKEMONS_HOUSE 26
#define MAP_MR_POKEMONS_HOUSE 10
#define MR_POKEMONS_HOUSE_WIDTH 4
#define MR_POKEMONS_HOUSE_HEIGHT 4

#define GROUP_ROUTE_31_VIOLET_GATE 26
#define MAP_ROUTE_31_VIOLET_GATE 11
#define ROUTE_31_VIOLET_GATE_WIDTH 5
#define ROUTE_31_VIOLET_GATE_HEIGHT 4


#define NUM_MAP_GROUPS 26
