// sprite_anim_struct members (see macros/wram.asm)
enum {
    SPRITEANIMSTRUCT_INDEX,
    SPRITEANIMSTRUCT_FRAMESET_ID,
    SPRITEANIMSTRUCT_ANIM_SEQ_ID,
    SPRITEANIMSTRUCT_TILE_ID,
    SPRITEANIMSTRUCT_XCOORD,
    SPRITEANIMSTRUCT_YCOORD,
    SPRITEANIMSTRUCT_XOFFSET,
    SPRITEANIMSTRUCT_YOFFSET,
    SPRITEANIMSTRUCT_DURATION,
    SPRITEANIMSTRUCT_DURATIONOFFSET,
    SPRITEANIMSTRUCT_FRAME,
    SPRITEANIMSTRUCT_JUMPTABLE_INDEX,
    SPRITEANIMSTRUCT_VAR1,
    SPRITEANIMSTRUCT_VAR2,
    SPRITEANIMSTRUCT_VAR3,
    SPRITEANIMSTRUCT_VAR4,
    SPRITEANIMSTRUCT_LENGTH,
};
#define NUM_SPRITE_ANIM_STRUCTS 10 // see wSpriteAnimationStructs

// wSpriteAnimDict keys (see wram.asm)
// UnusedSpriteAnimGFX indexes (see data/sprite_anims/unused_gfx.asm)
enum {
    SPRITE_ANIM_DICT_DEFAULT,      // 0
    SPRITE_ANIM_DICT_GS_INTRO,     // 1
    SPRITE_ANIM_DICT_GS_INTRO_2,   // 2
    SPRITE_ANIM_DICT_TEXT_CURSOR = 5,  // 5
    SPRITE_ANIM_DICT_GS_SPLASH,    // 6
    SPRITE_ANIM_DICT_SLOTS,        // 7
    SPRITE_ANIM_DICT_ARROW_CURSOR, // 8
    NUM_SPRITE_ANIM_GFX,
};

// wSpriteAnimDict size (see wram.asm)
#define NUM_SPRITEANIMDICT_ENTRIES 10

// SpriteAnimSeqData indexes (see data/sprite_anims/#define s ences.asm)
enum {
    SPRITE_ANIM_INDEX_PARTY_MON,                 // 00
    SPRITE_ANIM_INDEX_GS_INTRO_BUBBLE,           // 01
    SPRITE_ANIM_INDEX_GS_INTRO_SHELLDER,         // 02
    SPRITE_ANIM_INDEX_GS_INTRO_MAGIKARP,         // 03
    SPRITE_ANIM_INDEX_UNUSED_INTRO_AERODACTYL,   // 04
    SPRITE_ANIM_INDEX_GS_INTRO_LAPRAS,           // 05
    SPRITE_ANIM_INDEX_GS_INTRO_NOTE,             // 06
    SPRITE_ANIM_INDEX_GS_INTRO_INVISIBLE_NOTE,   // 07
    SPRITE_ANIM_INDEX_GS_INTRO_JIGGLYPUFF,       // 08
    SPRITE_ANIM_INDEX_GS_INTRO_PIKACHU,          // 09
    SPRITE_ANIM_INDEX_GS_INTRO_PIKACHU_TAIL,     // 0a
    SPRITE_ANIM_INDEX_GS_INTRO_FIREBALL,         // 0b
    SPRITE_ANIM_INDEX_GS_INTRO_CHIKORITA,        // 0c
    SPRITE_ANIM_INDEX_GS_INTRO_CYNDAQUIL,        // 0d
    SPRITE_ANIM_INDEX_GS_INTRO_TOTODILE,         // 0e
    SPRITE_ANIM_INDEX_GS_TITLE_TRAIL,            // 0f
    SPRITE_ANIM_INDEX_UNUSED_PIKACHU,            // 10
    SPRITE_ANIM_INDEX_UNUSED_PIKACHU_TAIL,       // 11
    SPRITE_ANIM_INDEX_UNUSED_NOTE,               // 12
    SPRITE_ANIM_INDEX_UNUSED_JIGGLYPUFF,         // 13
    SPRITE_ANIM_INDEX_NAMING_SCREEN_CURSOR,      // 14
    SPRITE_ANIM_INDEX_GAMEFREAK_LOGO,            // 15
    SPRITE_ANIM_INDEX_GS_GAMEFREAK_LOGO_STAR,    // 16
    SPRITE_ANIM_INDEX_GS_GAMEFREAK_LOGO_SPARKLE, // 17
    SPRITE_ANIM_INDEX_SLOTS_GOLEM,               // 18
    SPRITE_ANIM_INDEX_SLOTS_CHANSEY,             // 19
    SPRITE_ANIM_INDEX_SLOTS_EGG,                 // 1a
    SPRITE_ANIM_INDEX_COMPOSE_MAIL_CURSOR,       // 1b
    SPRITE_ANIM_INDEX_RED_WALK,                  // 1c
    SPRITE_ANIM_INDEX_UNUSED_CURSOR,             // 1d
    SPRITE_ANIM_INDEX_MEMORY_GAME_CURSOR,        // 1e
    SPRITE_ANIM_INDEX_POKEGEAR_ARROW,            // 1f
    SPRITE_ANIM_INDEX_TRADE_POKE_BALL,           // 20
    SPRITE_ANIM_INDEX_TRADE_POOF,                // 21
    SPRITE_ANIM_INDEX_TRADE_TUBE_BULGE,          // 22
    SPRITE_ANIM_INDEX_TRADEMON_ICON,             // 23
    SPRITE_ANIM_INDEX_TRADEMON_BUBBLE,           // 24
    SPRITE_ANIM_INDEX_EVOLUTION_BALL_OF_LIGHT,   // 25
    SPRITE_ANIM_INDEX_RADIO_TUNING_KNOB,         // 26
    SPRITE_ANIM_INDEX_MAGNET_TRAIN_RED,          // 27
    SPRITE_ANIM_INDEX_LEAF,                      // 28
    SPRITE_ANIM_INDEX_CUT_TREE,                  // 29
    SPRITE_ANIM_INDEX_FLY_LEAF,                  // 2a
    SPRITE_ANIM_INDEX_EGG_CRACK,                 // 2b
    SPRITE_ANIM_INDEX_GS_INTRO_HO_OH_LUGIA,      // 2c
    SPRITE_ANIM_INDEX_HEADBUTT,                  // 2d
    SPRITE_ANIM_INDEX_EGG_HATCH,                 // 2e
    NUM_SPRITE_ANIM_INDEXES,
};

// DoAnimFrame.Jumptable indexes (see engine/gfx/sprite_anims.asm)
enum {
    SPRITE_ANIM_SEQ_NULL,                        // 00
    SPRITE_ANIM_SEQ_PARTY_MON,                   // 01
    SPRITE_ANIM_SEQ_PARTY_MON_SWITCH,            // 02
    SPRITE_ANIM_SEQ_PARTY_MON_SELECTED,          // 03
    SPRITE_ANIM_SEQ_GS_INTRO_BUBBLE,             // 04
    SPRITE_ANIM_SEQ_GS_INTRO_SHELLDER,           // 05
    SPRITE_ANIM_SEQ_GS_INTRO_MAGIKARP,           // 06
    SPRITE_ANIM_SEQ_UNUSED_INTRO_AERODACTYL,     // 07
    SPRITE_ANIM_SEQ_GS_INTRO_LAPRAS,             // 08
    SPRITE_ANIM_SEQ_GS_INTRO_NOTE,               // 09
    SPRITE_ANIM_SEQ_GS_INTRO_JIGGLYPUFF,         // 0a
    SPRITE_ANIM_SEQ_GS_INTRO_PIKACHU,            // 0b
    SPRITE_ANIM_SEQ_GS_INTRO_PIKACHU_TAIL,       // 0c
    SPRITE_ANIM_SEQ_GS_INTRO_FIREBALL,           // 0d
    SPRITE_ANIM_SEQ_GS_INTRO_CHIKORITA_TOTODILE, // 0e
    SPRITE_ANIM_SEQ_GS_INTRO_CYNDAQUIL,          // 0f
    SPRITE_ANIM_SEQ_GS_TITLE_TRAIL,              // 10
    SPRITE_ANIM_SEQ_UNUSED_PIKACHU,              // 11
    SPRITE_ANIM_SEQ_UNUSED_PIKACHU_TAIL,         // 12
    SPRITE_ANIM_SEQ_UNUSED_NOTE,                 // 13
    SPRITE_ANIM_SEQ_UNUSED_JIGGLYPUFF,           // 14
    SPRITE_ANIM_SEQ_NAMING_SCREEN_CURSOR,        // 15
    SPRITE_ANIM_SEQ_GAMEFREAK_LOGO,              // 16
    SPRITE_ANIM_SEQ_GS_GAMEFREAK_LOGO_STAR,      // 17
    SPRITE_ANIM_SEQ_GS_GAMEFREAK_LOGO_SPARKLE,   // 18
    SPRITE_ANIM_SEQ_SLOTS_GOLEM,                 // 19
    SPRITE_ANIM_SEQ_SLOTS_CHANSEY,               // 1a
    SPRITE_ANIM_SEQ_SLOTS_EGG,                   // 1b
    SPRITE_ANIM_SEQ_MAIL_CURSOR,                 // 1c
    SPRITE_ANIM_SEQ_UNUSED_CURSOR,               // 1d
    SPRITE_ANIM_SEQ_MEMORY_GAME_CURSOR,          // 1e
    SPRITE_ANIM_SEQ_POKEGEAR_ARROW,              // 1f
    SPRITE_ANIM_SEQ_TRADE_POKE_BALL,             // 20
    SPRITE_ANIM_SEQ_TRADE_TUBE_BULGE,            // 21
    SPRITE_ANIM_SEQ_TRADEMON_IN_TUBE,            // 22
    SPRITE_ANIM_SEQ_REVEAL_NEW_MON,              // 23
    SPRITE_ANIM_SEQ_RADIO_TUNING_KNOB,           // 24
    SPRITE_ANIM_SEQ_CUT_LEAVES,                  // 25
    SPRITE_ANIM_SEQ_FLY_FROM,                    // 26
    SPRITE_ANIM_SEQ_FLY_LEAF,                    // 27
    SPRITE_ANIM_SEQ_FLY_TO,                      // 28
    SPRITE_ANIM_SEQ_GS_INTRO_HO_OH_LUGIA,        // 29
    NUM_SPRITE_ANIM_SEQS,
};

// SpriteAnimFrameData indexes (see data/sprite_anims/framesets.asm)
enum {
    SPRITE_ANIM_FRAMESET_00,                        // 00
    SPRITE_ANIM_FRAMESET_PARTY_MON,                 // 01
    SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_MAIL,       // 02
    SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_ITEM,       // 03
    SPRITE_ANIM_FRAMESET_GS_INTRO_BUBBLE,           // 04
    SPRITE_ANIM_FRAMESET_GS_INTRO_SHELLDER,         // 05
    SPRITE_ANIM_FRAMESET_GS_INTRO_MAGIKARP,         // 06
    SPRITE_ANIM_FRAMESET_UNUSED_INTRO_AERODACTYL,   // 07
    SPRITE_ANIM_FRAMESET_GS_INTRO_LAPRAS,           // 08
    SPRITE_ANIM_FRAMESET_GS_INTRO_NOTE,             // 09
    SPRITE_ANIM_FRAMESET_GS_INTRO_INVISIBLE_NOTE,   // 0a
    SPRITE_ANIM_FRAMESET_GS_INTRO_JIGGLYPUFF,       // 0b
    SPRITE_ANIM_FRAMESET_GS_INTRO_JIGGLYPUFF_2,     // 0c
    SPRITE_ANIM_FRAMESET_GS_INTRO_PIKACHU,          // 0d
    SPRITE_ANIM_FRAMESET_GS_INTRO_PIKACHU_2,        // 0e
    SPRITE_ANIM_FRAMESET_GS_INTRO_PIKACHU_3,        // 0f
    SPRITE_ANIM_FRAMESET_GS_INTRO_PIKACHU_TAIL,     // 10
    SPRITE_ANIM_FRAMESET_GS_INTRO_PIKACHU_TAIL_2,   // 11
    SPRITE_ANIM_FRAMESET_GS_INTRO_FIREBALL,         // 12
    SPRITE_ANIM_FRAMESET_GS_INTRO_CHIKORITA,        // 13
    SPRITE_ANIM_FRAMESET_GS_INTRO_CYNDAQUIL,        // 14
    SPRITE_ANIM_FRAMESET_GS_INTRO_TOTODILE,         // 15
    SPRITE_ANIM_FRAMESET_GS_TITLE_TRAIL,            // 16
    SPRITE_ANIM_FRAMESET_UNUSED_PIKACHU,            // 17
    SPRITE_ANIM_FRAMESET_UNUSED_PIKACHU_2,          // 18
    SPRITE_ANIM_FRAMESET_UNUSED_PIKACHU_3,          // 19
    SPRITE_ANIM_FRAMESET_TEXT_ENTRY_CURSOR,         // 1a
    SPRITE_ANIM_FRAMESET_TEXT_ENTRY_CURSOR_BIG,     // 1b
    SPRITE_ANIM_FRAMESET_GAMEFREAK_LOGO,            // 1c
    SPRITE_ANIM_FRAMESET_GS_GAMEFREAK_LOGO_STAR,    // 1d
    SPRITE_ANIM_FRAMESET_GS_GAMEFREAK_LOGO_SPARKLE, // 1e
    SPRITE_ANIM_FRAMESET_SLOTS_GOLEM,               // 1f
    SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY,             // 20
    SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY_2,           // 21
    SPRITE_ANIM_FRAMESET_SLOTS_EGG,                 // 22
    SPRITE_ANIM_FRAMESET_RED_WALK,                  // 23
    SPRITE_ANIM_FRAMESET_STILL_CURSOR,              // 24
    SPRITE_ANIM_FRAMESET_TRADE_POKE_BALL,           // 25
    SPRITE_ANIM_FRAMESET_TRADE_POKE_BALL_WOBBLE,    // 26
    SPRITE_ANIM_FRAMESET_TRADE_POOF,                // 27
    SPRITE_ANIM_FRAMESET_TRADE_TUBE_BULGE,          // 28
    SPRITE_ANIM_FRAMESET_TRADEMON_ICON,             // 29
    SPRITE_ANIM_FRAMESET_TRADEMON_BUBBLE,           // 2a
    SPRITE_ANIM_FRAMESET_EVOLUTION_BALL_OF_LIGHT,   // 2b
    SPRITE_ANIM_FRAMESET_RADIO_TUNING_KNOB,         // 2c
    SPRITE_ANIM_FRAMESET_MAGNET_TRAIN_RED,          // 2d
    SPRITE_ANIM_FRAMESET_UNUSED_2E,                 // 2e
    SPRITE_ANIM_FRAMESET_LEAF,                      // 2f
    SPRITE_ANIM_FRAMESET_CUT_TREE,                  // 30
    SPRITE_ANIM_FRAMESET_EGG_CRACK,                 // 31
    SPRITE_ANIM_FRAMESET_EGG_HATCH_1,               // 32
    SPRITE_ANIM_FRAMESET_EGG_HATCH_2,               // 33
    SPRITE_ANIM_FRAMESET_EGG_HATCH_3,               // 34
    SPRITE_ANIM_FRAMESET_EGG_HATCH_4,               // 35
    SPRITE_ANIM_FRAMESET_GS_INTRO_HO_OH_LUGIA,      // 36
    SPRITE_ANIM_FRAMESET_HEADBUTT,                  // 37
    NUM_SPRITE_ANIM_FRAMESETS,
};

// SpriteAnimOAMData indexes (see data/sprite_anims/oam.asm)
enum {
    SPRITE_ANIM_OAMSET_RED_WALK_1,                  // 00
    SPRITE_ANIM_OAMSET_RED_WALK_2,                  // 01
    SPRITE_ANIM_OAMSET_GS_INTRO_BUBBLE_1,           // 02
    SPRITE_ANIM_OAMSET_GS_INTRO_BUBBLE_2,           // 03
    SPRITE_ANIM_OAMSET_GS_INTRO_SHELLDER_1,         // 04
    SPRITE_ANIM_OAMSET_GS_INTRO_SHELLDER_2,         // 05
    SPRITE_ANIM_OAMSET_GS_INTRO_MAGIKARP_1,         // 06
    SPRITE_ANIM_OAMSET_GS_INTRO_MAGIKARP_2,         // 07
    SPRITE_ANIM_OAMSET_UNUSED_INTRO_AERODACTYL,     // 08
    SPRITE_ANIM_OAMSET_GS_INTRO_LAPRAS_1,           // 09
    SPRITE_ANIM_OAMSET_GS_INTRO_LAPRAS_2,           // 0a
    SPRITE_ANIM_OAMSET_GS_INTRO_LAPRAS_3,           // 0b
    SPRITE_ANIM_OAMSET_GS_INTRO_NOTE,               // 0c
    SPRITE_ANIM_OAMSET_GS_INTRO_INVISIBLE_NOTE,     // 0d
    SPRITE_ANIM_OAMSET_GS_INTRO_JIGGLYPUFF_1,       // 0e
    SPRITE_ANIM_OAMSET_GS_INTRO_JIGGLYPUFF_2,       // 0f
    SPRITE_ANIM_OAMSET_GS_INTRO_JIGGLYPUFF_3,       // 10
    SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_1,          // 11
    SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_2,          // 12
    SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_3,          // 13
    SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_4,          // 14
    SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_TAIL_1,     // 15
    SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_TAIL_2,     // 16
    SPRITE_ANIM_OAMSET_GS_INTRO_PIKACHU_TAIL_3,     // 17
    SPRITE_ANIM_OAMSET_GS_INTRO_SMALL_FIREBALL,     // 18
    SPRITE_ANIM_OAMSET_GS_INTRO_MED_FIREBALL,       // 19
    SPRITE_ANIM_OAMSET_GS_INTRO_BIG_FIREBALL,       // 1a
    SPRITE_ANIM_OAMSET_GS_INTRO_CHIKORITA,          // 1b
    SPRITE_ANIM_OAMSET_GS_INTRO_CYNDAQUIL,          // 1c
    SPRITE_ANIM_OAMSET_GS_INTRO_TOTODILE,           // 1d
    SPRITE_ANIM_OAMSET_GS_TITLE_TRAIL_1,            // 1e
    SPRITE_ANIM_OAMSET_GS_TITLE_TRAIL_2,            // 1f
    SPRITE_ANIM_OAMSET_TEXT_ENTRY_CURSOR,           // 20
    SPRITE_ANIM_OAMSET_TEXT_ENTRY_CURSOR_BIG,       // 21
    SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO,           // 22
    SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO_STAR,      // 23
    SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO_SPARKLE_1, // 24
    SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO_SPARKLE_2, // 25
    SPRITE_ANIM_OAMSET_GS_GAMEFREAK_LOGO_SPARKLE_3, // 26
    SPRITE_ANIM_OAMSET_SLOTS_GOLEM_1,               // 27
    SPRITE_ANIM_OAMSET_SLOTS_GOLEM_2,               // 28
    SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_1,             // 29
    SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_2,             // 2a
    SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_3,             // 2b
    SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_4,             // 2c
    SPRITE_ANIM_OAMSET_SLOTS_CHANSEY_5,             // 2d
    SPRITE_ANIM_OAMSET_SLOTS_EGG,                   // 2e
    SPRITE_ANIM_OAMSET_STILL_CURSOR,                // 2f
    SPRITE_ANIM_OAMSET_TRADE_POKE_BALL_1,           // 30
    SPRITE_ANIM_OAMSET_TRADE_POKE_BALL_2,           // 31
    SPRITE_ANIM_OAMSET_TRADE_POOF_1,                // 32
    SPRITE_ANIM_OAMSET_TRADE_POOF_2,                // 33
    SPRITE_ANIM_OAMSET_TRADE_POOF_3,                // 34
    SPRITE_ANIM_OAMSET_TRADE_TUBE_BULGE_1,          // 35
    SPRITE_ANIM_OAMSET_TRADE_TUBE_BULGE_2,          // 36
    SPRITE_ANIM_OAMSET_TRADEMON_ICON_1,             // 37
    SPRITE_ANIM_OAMSET_TRADEMON_ICON_2,             // 38
    SPRITE_ANIM_OAMSET_TRADEMON_BUBBLE,             // 39
    SPRITE_ANIM_OAMSET_EVOLUTION_BALL_OF_LIGHT_1,   // 3a
    SPRITE_ANIM_OAMSET_EVOLUTION_BALL_OF_LIGHT_2,   // 3b
    SPRITE_ANIM_OAMSET_RADIO_TUNING_KNOB,           // 3c
    SPRITE_ANIM_OAMSET_PARTY_MON_WITH_MAIL_1,       // 3d
    SPRITE_ANIM_OAMSET_PARTY_MON_WITH_MAIL_2,       // 3e
    SPRITE_ANIM_OAMSET_PARTY_MON_WITH_ITEM_1,       // 3f
    SPRITE_ANIM_OAMSET_PARTY_MON_WITH_ITEM_2,       // 40
    SPRITE_ANIM_OAMSET_MAGNET_TRAIN_RED_1,          // 41
    SPRITE_ANIM_OAMSET_MAGNET_TRAIN_RED_2,          // 42
    SPRITE_ANIM_OAMSET_UNUSED_43,                   // 43
    SPRITE_ANIM_OAMSET_UNUSED_44,                   // 44
    SPRITE_ANIM_OAMSET_UNUSED_45,                   // 45
    SPRITE_ANIM_OAMSET_UNUSED_46,                   // 46
    SPRITE_ANIM_OAMSET_UNUSED_47,                   // 47
    SPRITE_ANIM_OAMSET_UNUSED_48,                   // 48
    SPRITE_ANIM_OAMSET_UNUSED_49,                   // 49
    SPRITE_ANIM_OAMSET_UNUSED_4A,                   // 4a
    SPRITE_ANIM_OAMSET_UNUSED_4B,                   // 4b
    SPRITE_ANIM_OAMSET_UNUSED_4C,                   // 4c
    SPRITE_ANIM_OAMSET_UNUSED_4D,                   // 4d
    SPRITE_ANIM_OAMSET_UNUSED_4E,                   // 4e
    SPRITE_ANIM_OAMSET_LEAF,                        // 4f
    SPRITE_ANIM_OAMSET_TREE_1,                      // 50
    SPRITE_ANIM_OAMSET_CUT_TREE_2,                  // 51
    SPRITE_ANIM_OAMSET_CUT_TREE_3,                  // 52
    SPRITE_ANIM_OAMSET_CUT_TREE_4,                  // 53
    SPRITE_ANIM_OAMSET_EGG_CRACK,                   // 54
    SPRITE_ANIM_OAMSET_EGG_HATCH,                   // 55
    SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_1,      // 56
    SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_2,      // 57
    SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_3,      // 58
    SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_4,      // 59
    SPRITE_ANIM_OAMSET_GS_INTRO_HO_OH_LUGIA_5,      // 5a
    SPRITE_ANIM_OAMSET_HEADBUTT_TREE_2,             // 5b
    NUM_SPRITE_ANIM_OAMSETS,
};
