void UpdateBGMapBuffer(void);
void WaitTop(void);
void UpdateBGMap(void);
void Serve1bppRequest(void);
void Serve2bppRequest(void);
void AnimateTileset(void);
void Video_DummyFunction(void);
void EnableSpriteDisplay(void);
void FillBGMap0WithBlack(void);
