int UpdateBGMapBuffer();
int WaitTop();
int UpdateBGMap();
int Serve1bppRequest();
int Serve2bppRequest();
int AnimateTileset();
int Video_DummyFunction();
int EnableSpriteDisplay();
int FillBGMap0WithBlack();
